### ISSUE TITLE
Compression Featured Quote is incorrect

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1002]
Just spotted during the French review that the Compression chapter featured quote on the home page is actually a repeat of the JavaScript quote!

- [x] English version - fixed in #1001
- [x] French version - @allemas could you fix this based on #1001 ?
- [x] Japanese - @ksakae1216 could you fix this based on #1001 ?
