### ISSUE TITLE
Increase pytest coverage

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1229]
@Super-Fly did some excellent work in #949 and #1176 to refactor out Python code.

We should look to increase our pytest coverage to test some of these function/helper files.

- [x] - Add Coverage reports - @bazzadp - #1555 
- [x] - `server/init.py` (69%) - @bazzadp - #1853
- [x] - `server/config.py` (96%) - @AbbyTsai - #1605
- [x] - `server/errors.py` (65%) - @bazzadp - #1853
- [x] - `server/helpers.py` (31%) - @bazzadp - #1576
- [x] - `server/language.py` (78%) - @bazzadp - #1853
- [x] - `server/routes.py` (58%) - @bazzadp - #1607 
- [x] - `server/validate.py` (60%) - @bazzadp - #1523

Latest coverage report (will update this as we merge each PR):

```
---------- coverage: platform darwin, python 3.8.0-final-0 -----------
Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
server/__init__.py                 39      1    97%   20
server/config.py                   69      0   100%
server/csp.py                       1      0   100%
server/errors.py                   23      7    70%   11, 16-17, 27-28, 33-34
server/feature_policy.py            1      0   100%
server/helpers.py                 126      0   100%
server/language.py                 33      1    97%   10
server/routes.py                   72      0   100%
server/tests/__init__.py            0      0   100%
server/tests/config_test.py        37      0   100%
server/tests/helpers_test.py      184      0   100%
server/tests/routes_test.py        69      0   100%
server/tests/validate_test.py      52      0   100%
server/validate.py                 79      5    94%   39-41, 66-67
-------------------------------------------------------------
TOTAL                             785     14    98%

Required test coverage of 95% reached. Total coverage: 98.22%
================================== 105 passed, 21 warnings in 6.79s ===
```

**Comment by bazzadp** [comment]
Adding a coverage checker in #1555 and Editing the first comment to add the tasks that need completing.

Would love to get to 100% coverage and think that's easily achievable.

We can use `# pragma no cover` if we absolutely have to to exclude lines we don't need to test (e.g. Flask calls), but ideal we add at least one test for every line and [Flask gives guidance on how to test Flask apps](https://flask.palletsprojects.com/en/1.1.x/testing/).

**Comment by rviscomi** [comment]
Adding test coverage can be thankless work, so I want to make sure to say **thank you** @AbbyTsai and @bazzadp for working on this!

**Comment by bazzadp** [comment]
It appeals to my meticulous nature. 😁
