### ISSUE TITLE
Edit 2020 Chapters

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1432]
Part I. Page Content
 - [x]  - [Chapter 1: CSS](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/css.md) - @bazzadp #1846
 - [x]  - [Chapter 2: JavaScript](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/javascript.md) - @rviscomi #1737
 - [x]  - [Chapter 3: Markup](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/markup.md) - @rviscomi #1435 and #1604 
 - [x]  - [Chapter 4: Fonts](https://github.com/HTTPArchive/almanac.httparchive.org/tree/mainsrc/content/en/2020/fonts.md) - @bazzadp #1816 and #1868
 - [x]  - [Chapter 5: Media](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/media.md) - @bazzadp #1882
 - [x]  - [Chapter 6: Third Parties](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/third-parties.md) - @bazzadp - #1877 

Part II. User Experience
 - [x]  - [Chapter 7: SEO](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/seo.md) - @rviscomi 
 - [x]  - [Chapter 8: Accessibility](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/accessibility.md) - @bazzadp - #1752 
 - [x]  - [Chapter 9: Performance](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/performance) - @bazzadp - #1622 
 - [x]  - [Chapter 10: Privacy](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/privacy.md) - @bazzadp - #1672 and #1935
 - [x]  - [Chapter 11: Security](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/security.md) - @bazzadp - #1927
 - [x]  - [Chapter 12: Mobile Web](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/mobile-web.md) - @exterkamp - #1758
 - [x]  - [Chapter 13: Capabilities](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/capabilities.md) - @rviscomi #1492
 - [x]  - [Chapter 14: PWA](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/pwa.md) - @bazzadp - #1924

Part III. Content Publishing
 - [x]  - [Chapter 15: CMS](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/cms.md) - @bazzadp - #1624
 - [x]  - [Chapter 16: Ecommerce](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/ecommerce.md) - @bazzadp - #1891 
 - [x]  - [Chapter 17: Jamstack](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/jamstack.md) - @bazzadp - #1665 and #1938
 
Part IV. Content Distribution
 - [x]  - [Chapter 18: Page Weight](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/page-weight.md) - @bazzadp - #1894 
 - [x]  - [Chapter 19: Compression](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/compression.md) - @exterkamp - #1688 #1911
 - [x]  - [Chapter 20: Caching](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/caching.md) - @bazzadp - #1915 
 - [x]  - [Chapter 21: Resource Hints](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/resource-hints.md) - @exterkamp - #1664
 - [x]  - [Chapter 22: HTTP/2](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020/http2.md) - @rviscomi - #1618

**Comment by bazzadp** [comment]
Same rules as last time @HTTPArchive/editors - grab a chapter when you see one free and claim it by tagging your name next to the first issue and then submit a PR with the original authors. Links to chapters available in [our issue tracker](https://github.com/HTTPArchive/almanac.httparchive.org/issues/989)

**Comment by rviscomi** [comment]
Pro tip for editors who spot something that should be changed but the fix isn't ready yet (for example a link to an unlaunched chapter), use a Jinja comment starting with `TODO` so it's annotated in the markdown file, easily discoverable, and not included in the HTML output.

```md
{# TODO: Link directly to the relevant Accessibility section. #}
We identified 2,863 different values for the `lang` attribute on the `html` start tag (compare that to the [7,117 spoken languages](https://www.ethnologue.com/guides/how-many-languages) as per Ethnologue). Almost all of them, [according to the Accessibility chapter](./accessibility), seem valid.
```

**Comment by bazzadp** [comment]
Tagging those that expressed an interest in editing in #922 . If anyone else is interested (@HTTPArchive/editors ?) then feel free to add your self to Assignees.

The [Capabilities chapter](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2020/capabilities.md) is good to go for editing if anyone wants to grab it?

**Comment by bazzadp** [comment]
Added two new suggestions to Editors Guide:

* Check previous years chapters table of contents and flag to authors if any messing pieces, to ensure they didn't accidentally leave out an important section
* Check print version (add `?print` to URL) to ensure all images load (check for console errors is the easiest way of checking this).

**Comment by rviscomi** [comment]
@bazzadp @rachellcostello  CMS is ready for editing, would either of you like to take that one?

**Comment by bazzadp** [comment]
HTTP/2 is ready for editing.

I'll have a look at CMS in next day or two if no one else grabs it.

**Comment by rviscomi** [comment]
@HTTPArchive/editors Resource Hints is now ready for editing

**Comment by bazzadp** [comment]
@HTTPArchive/editors HTTP/2 and SEO is ready for editing

**Comment by rviscomi** [comment]
Added a note to the editors' wiki about using the `numeric` class on tabular figures. See this before and after:

![image](https://user-images.githubusercontent.com/1120896/100973855-5b705b80-3509-11eb-8c96-6ede22d4be03.png)
![image](https://user-images.githubusercontent.com/1120896/100973881-63300000-3509-11eb-9f00-f69394420dbd.png)

It's a minor change but right-aligning makes the decimal points line up and is easier to read.

To make this conversion, I'll "copy outer HTML" of the rendered table in DevTools and replace the markdown table with it. Don't forget to remove the `markdown` class from the `figure`!

![image](https://user-images.githubusercontent.com/1120896/100974016-970b2580-3509-11eb-9d40-f089af8711a7.png)

Before:

```html
<figure markdown>
| Protocol | Desktop | Mobile |
| -------- | ------- | ------ |
| HTTP/1.1 | 36.05%  | 34.04% |
| HTTP/2   | 63.95%  | 65.96% |
<figcaption>..,</figcaption>
</figure>
```

After

```html
<figure>
  <table>
    <thead>
      <tr>
        <th>Protocol</th>
        <th>Desktop</th>
        <th>Mobile</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>HTTP/1.1</td>
        <td class="numeric">36.05%</td>
        <td class="numeric">34.04%</td>
      </tr>
      <tr>
        <td>HTTP/2</td>
        <td class="numeric">63.95%</td>
        <td class="numeric">65.96%</td>
      </tr>
    </tbody>
  </table>
  <figcaption>...</figcaption>
</figure>
```

**Comment by bazzadp** [comment]
@HTTPArchive/editors PWA and Jamstack are ready for editing.

**Comment by bazzadp** [comment]
Compression and Caching ready for editing.
