### ISSUE TITLE
Code cleanup to move away from 2019 as a base

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1558]
Currently we have 2019 as a "base" for a lot of our code, and 2020 is an extension of that. I'd like to clean this up properly, to make it more obvious what's base and what's 2019. This will allow greater multi-year support, avoid confusion and also allow Translations to support just 2020, whereas currently they must support both 2019 and 2020.

Tasks to do:
- [x] - Move `src/templates/base/2019/` to `src/templates/base/` - #1559
- [x] - Separate language templates from, for example, `src/templates/en/2019/` to `src/templates/en/`, leaving behind smaller 2020-like files in the 2019 directory. - #1568 
- [x] - Rename `2019.css` to `almanac.css` - #1918 
- [ ] - Decide what to do with the Chapter Hero Images (currently in 2019 image dir). Duplicate in 2020? Fallback to 2019 if not exists in 2020 (how will this scale)? Move to separate Hero-Images dir (but then how to override a chapter in future - or is that next year's problem)? - #1920 

None of these are particularly difficult but opening this issue to track and to allow smaller PRs to handle them. Would be good to get a good few of them done now while waiting on chapters.
