### ISSUE TITLE
Publish 2020 Web Almanac "stories"

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1571]
This issue will track the plan to publish one or more Web Almanac [stories](https://amp.dev/about/stories/). The purpose of the stories is to create an engaging way to showcase the stats from each chapter and market the report in web searches so that we drive organic growth in addition to all of our other social media marketing efforts. The current thinking is to create one story for each of the four distinct groups of chapters, grouped by Part I through Part IV as seen in the [ToC](https://almanac.httparchive.org/en/2020/table-of-contents). We'll highlight one or two of the most interesting stats from each chapter in each "page" of the story. Basically, this is secondary marketing material to attract more readers. We're not changing anything about the way the content itself is published.

Here are a few concrete tasks to publish the stories:

- Compile a list of the most interesting stats from all 22 chapters. For chapters whose markdown drafts are already created, we can reuse their featured stats metadata.
- I will coordinate with an external contractor to develop the stories using these stats and our site design/illustrations as inspiration.
_(Side note: Google is an HTTP Archive sponsor and will be covering the contractor's costs directly. For context, we also contracted out the original Web Almanac design and illustrations.)_
- When the stories are delivered to us, we'll need to serve them from the website. They will be developed using the WordPress editor so we'll need to make sure that all of the static resources are addressed and served according to our own directory structure and not the WordPress defaults.
- Implement SEO best practices to make sure the stories are indexable and discoverable in search tools. Here's a helpful [SEO guide to stories](https://developers.google.com/search/docs/guides/web-stories-creation-best-practices).

This is something that should go live on or shortly after the big launch on December 9.

Once above is released, we should create a story for each section:

- [x] - Story 1 - Part I. Page Content - #1800
- [x] - Story 2 - Part II. User Experience - #1864 
- [x] - Story 3 - Part III. Content Publishing - #1880
- [x] - Story 4 - Part IV. Content Distribution - #1898 
- [x] - Updated stories created with 2019 stats as chapters were not ready - #1900

**Comment by bazzadp** [comment]
All done so closing. Thanks for you work on this @swissspidy !

Any ideas how long these take to appear in SERPs? Been googling for "Web Almanac" occasionally but nothing yet, though it does show in AMP section of Google Search Console.

**Comment by swissspidy** [comment]
> Any ideas how long these take to appear in SERPs? Been googling for "Web Almanac" occasionally but nothing yet, though it does show in AMP section of Google Search Console.

Searching for `inurl:https://almanac.httparchive.org/en/2020/stories/` I already see three results

**Comment by bazzadp** [comment]
Agreed and had seen them before. But presume the whole point of this is to try to get them to appear in a “stories section” for other search terms? And I’ve not seen that yet.

Btw just released that final story and the fixes to the older ones. So imagine that’ll be four stories very soon!

**Comment by swissspidy** [comment]
The way stories are surfaced across Google Search and other areas depends on things like country and language, see https://developers.google.com/search/docs/guides/enable-web-stories. In my case, I just saw them as regular single search results.

**Comment by bazzadp** [comment]
Looks like a lot are US only so guess I, being based in Ireland, have less chance of seeing them.

OK a couple more questions for you if you don't mind.

First of all, I do a search for `inurl:https://almanac.httparchive.org/en/2020/stories/` on my iphone and see the stories with the AMP lightning bolt. I click on it and it loads. However URL is google.ie because it's being served by AMP cache. So I click on little (i) icon and try to open real URL and I get this error:

![image](https://user-images.githubusercontent.com/10931297/104950017-d86f6b80-59b7-11eb-96a6-bf714a719e18.png)

Any ideas why? Weirdly I don't see that error in desktop Chrome in emulation mode but still doesn't open original URL.

Also discovered some page URLs in two of the stories so raised #1902 to fix that, but even the ones that have correct URLs have the problem so don't think it's that.

Secondly while in Chrome desktop in emulation mode I'm seeing lots of errors.

For example 404s:

![image](https://user-images.githubusercontent.com/10931297/104950389-782cf980-59b8-11eb-9e36-b00c8c189e9b.png)

Even though those images exist on our site when I convert the URL from this:
https://almanac-httparchive-org.cdn.ampproject.org/bv/s/almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4
to this:
https://almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4

But also random JavaScript errors (particularly using the (i) button):

![image](https://user-images.githubusercontent.com/10931297/104950477-a27eb700-59b8-11eb-95e3-2d322ff490a0.png)

Or when going back to SERPs (guessing I interrupted processing here so maybe this is not an error?):

![image](https://user-images.githubusercontent.com/10931297/104950512-b32f2d00-59b8-11eb-9fc0-f9c50e9d4352.png)

**Comment by swissspidy** [comment]
> First of all, I do a search for `inurl:https://almanac.httparchive.org/en/2020/stories/` on my iphone and see the stories with the AMP lightning bolt. I click on it and it loads. However URL is google.ie because it's being served by AMP cache. So I click on little (i) icon and try to open real URL and I get this error:
> 
> ![image](https://user-images.githubusercontent.com/10931297/104950017-d86f6b80-59b7-11eb-96a6-bf714a719e18.png)
> 
> Any ideas why? Weirdly I don't see that error in desktop Chrome in emulation mode but still doesn't open original URL.

I'm seeing the same on my phone, but no idea why this happens :/

> Also discovered some page URLs in two of the stories so raised #1902 to fix that, but even the ones that have correct URLs have the problem so don't think it's that.
> 
> Secondly while in Chrome desktop in emulation mode I'm seeing lots of errors.
> 
> For example 404s:
> 
> ![image](https://user-images.githubusercontent.com/10931297/104950389-782cf980-59b8-11eb-9e36-b00c8c189e9b.png)
> 
> Even though those images exist on our site when I convert the URL from this:
> [almanac-httparchive-org.cdn.ampproject.org/bv/s/almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4](https://almanac-httparchive-org.cdn.ampproject.org/bv/s/almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4)
> to this:
> [almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4](https://almanac.httparchive.org/static/stories/web-almanac-2020-content-publishing/WA_p3_slide_3.mp4)

Yup, can see that too, but it can be safely ignored I think. If the asset is not available on the Google AMP cache, it will simply load it from almanac.httparchive.org. So I can see the videos just fine.

> But also random JavaScript errors (particularly using the (i) button):
> 
> ![image](https://user-images.githubusercontent.com/10931297/104950477-a27eb700-59b8-11eb-95e3-2d322ff490a0.png)

Seems like a known issue:

https://github.com/ampproject/amphtml/issues/30798
https://github.com/ampproject/amphtml/issues/24490

> Or when going back to SERPs (guessing I interrupted processing here so maybe this is not an error?):
> 
> ![image](https://user-images.githubusercontent.com/10931297/104950512-b32f2d00-59b8-11eb-9fc0-f9c50e9d4352.png)

Hmm I can't seem to reproduce this one

**Comment by bazzadp** [comment]
Cheers for answers. AMP is so much fun!! 😉

> I'm seeing the same on my phone, but no idea why this happens :/

You on Android or iPhone out of interest? Wonder if we should raise this to the AMP team?

**Comment by swissspidy** [comment]
> Cheers for answers. AMP is so much fun!! 😉
> 
> > I'm seeing the same on my phone, but no idea why this happens :/
> 
> You on Android or iPhone out of interest? Wonder if we should raise this to the AMP team?

I'm on iPhone too. Opened an issue just in case as it happens with other stories as well: https://github.com/ampproject/amphtml/issues/32038
