### ISSUE TITLE
CSS 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2140]
# Part I Chapter 1: CSS

![CSS illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/css/hero_lg.jpg)

If you're interested in contributing to the CSS chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @meyerweb | @geekboysupreme @meyerweb | @j9t @svgeesus @argyleink @una @estelle @LeaVerou @rachelandrew @jabranr @tomhodgins | @rviscomi @thecraftysoul | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 CSS resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/css
[~google-sheets]: https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/css.md

**Comment by j9t** [comment]
Reviewer—interested and available.

**Comment by GeekBoySupreme** [comment]
Interested and available as an author. Can double up as an Editor (if necessary)

**Comment by rviscomi** [comment]
📟 Paging CSS 2020 crew: @LeaVerou @svgeesus @rachelandrew @fantasai @mirisuzanne @catalinred @dooman87 

Would any of you be interested to contribute to the CSS 2021 chapter? I'd especially like to see more 2020 authors become 2021 reviewers to help ease the transition and similarly I think 2020 reviewers would make great 2021 authors, being familiar with the process already. And 2020 analysts would make excellent 2021 analysts 😁

**Comment by svgeesus** [comment]
I'm happy to contribute again as author or, if there are many excited new authors, as reviewer.

**Comment by argyleink** [comment]
I'll be a reviewer 🙂

**Comment by una** [comment]
Happy to review!

**Comment by rviscomi** [comment]
@svgeesus would you be open to being the content team lead and drive the content planning/writing? You can coauthor with @GeekBoySupreme and anyone else who may be interested.

**Comment by estelle** [comment]
Please add me to the list of reviewers.

**Comment by LeaVerou** [comment]
I can review!

**Comment by rachelandrew** [comment]
I can review.

**Comment by rviscomi** [comment]
@meyerweb thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) by finding contributors to help with the analysis and any other reviewers/coauthors as needed
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140#issue-868435575
[~google-doc]: https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit?usp=sharing

**Comment by jabranr** [comment]
@rviscomi Interested and available as a reviewer

**Comment by rviscomi** [comment]
@meyerweb are you able to edit the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140#issue-868435575) to update the list of reviewers and check off the 0th milestone?

**Comment by meyerweb** [comment]
Author and reviewer volunteers added — welcome, all!  If I missed anyone, please let me know.

This is a good time to wish for things to analyze and talk about in CSS.  @bkardell had [a great suggestion in the accessibility issue](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2147#issuecomment-843422635):

>it strikes me that in neither the CSS nor Accessibility chapters in 2019/2020 is there any analysis on focus stying (including the disabling of) which is very relevant to a lot of conversations and would be great to have more facts on

What else?  Anything that hasn’t been done in the past that should be?  Anything that’s been done in the past we should drop?  Let’s hear ’em!

**Comment by meyerweb** [comment]
As a starting point for everyone, I’ve created a draft outline for the chapter on https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE with some proposed additions and hanging questions.

**Comment by thecraftysoul** [comment]
Interested as analyst

**Comment by rviscomi** [comment]
Welcome @thecraftysoul! To get started:

- Request edit access to the [chapter planning doc](https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit?usp=sharing)
- Add your name and email to the "Analysts" line
- Join the [#web-almanac-analysts](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on Slack
- Familiarize yourself with the [queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/css) and [results](https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit?usp=sharing) used by the CSS 2020 chapter (more info in the [SQL README](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/css/README.md)) as this year's analysis will reuse many of the same queries

@paulcalvano will be able to get you set up on our BigQuery project to ensure that all of your analysis is covered by us. Slack would be the best place to reach out if you have any analysis questions, otherwise for any chapter-specific questions, @meyerweb is the team lead and can assist you here on GitHub or in comments in the doc.

**Comment by meyerweb** [comment]
Here are the custom metrics we’ve so far thought about adding to the metrics collected for 2020 (apologies if I missed any in 2020 and have thus duplicated them here):

* `:focus` customization, and prevalence of `outline: 0`
* `:focus-visible` use
* Collecting generated content strings (e.g., `content: "Item "`)
* Formats of images called in CSS (GIF/JPG/PNG/WEBM/SVG/gradients)
* Number of images per style sheet
* Weight of images called in CSS
* Pixel sizes of images called in CSS
* `animation-duration` and `transition-duration` values
* `animation-delay` and `transition-delay` values
* Counts and percentage positions of animation keyframes
* CSS Ruby property usage
* Usage of CSS utility frameworks
* Usage of polyfills

Anything else anyone can think of?  You can see the full list [over at Google Docs](https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit#).

**Comment by rviscomi** [comment]
Reviewers (@j9t @svgeesus @argyleink @una @estelle @LeaVerou @rachelandrew @jabranr @tomhodgins) reminder to please request edit access to the doc and leave your feedback on the chapter outline. I'll try to add everyone whose email I already know.

**Comment by j9t** [comment]
(Had checked the doc last week—LGTM—, will keep monitoring this thread.)

**Comment by LeaVerou** [comment]
@meyerweb We should look into `@property` usage (% of pages using, median rules pp, stats about types, inherits, initial values), that's probably the hottest thing that happened to CSS in the past year.

**Comment by meyerweb** [comment]
> @meyerweb We should look into `@property` usage (% of pages using, median rules pp, stats about types, inherits, initial values), that's probably the hottest thing that happened to CSS in the past year.

Excellent suggestion; added.  Thank you!

**Comment by meyerweb** [comment]
Thank you to everyone who’s added ideas on the Google Doc.  I’ve responded to most and made changes accordingly, but did leave a questions or comments on a few (@una @svgeesus @rviscomi).  If you haven’t weighed in yet, there’s still a little time, so please do, either here or on the Google Doc.

**Comment by rviscomi** [comment]
@meyerweb the outline is looking great and [your list](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140#issuecomment-848025065) is really helpful to see what has changed since last year. It doesn't look like we'll need to add anything to the test pipeline at runtime. AFAICT everything can be measured using existing post-processing analysis, so we should be good to go. If you're happy with it you can check off [Milestone 1](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140#issue-868435575) above.

If anyone can spot a new metric that does depend on custom runtime metrics (querying the DOM, for example) please let me know!

**Comment by rviscomi** [comment]
All of the ~120 metrics from 2020 have been rerun and the results are available for review in the [chapter sheet](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit?usp=sharing). I'm still working on analyzing the 2021-specific metrics but needless to say there's already a ton of data ready to review.

Could you all take a look and leave a comment (request edit access if needed) if you see anything unexpected? With this much data it'll be a big help if we have multiple people reviewing it. Thanks everyone! 🙏

**Comment by meyerweb** [comment]
I reviewed and left some comments.  I still owe you some feedback on your questions about the new metrics, and  hope to have those answers to you by the end of the week.

**Comment by meyerweb** [comment]
How to look for CSS Ruby usage:

* Properties `ruby-position`, `ruby-align`, ruby-merge`, and `ruby-overhang`
* `display` values `ruby`, `ruby-base`, `ruby-text`, `ruby-base-container`, and `ruby-text-container

**Comment by meyerweb** [comment]
**How to identify use of a library**

* animate.css
	* HTML: `href=".*?animate[\.min]?.css"` in a `link` element
	* CSS: `\* animate.css` in a comment
* Bootstrap
	* HTML: `href=".*?bootstrap[\.min]?.css"` in a `link` element
	* CSS: `--bs-*` custom properties, `The Bootstrap Authors` in a comment
* Foundation
	* HTML: `foundation-icons.css` in a `link` element’s `href` attribute
	* CSS: `.fi-*` class names, `*zurb*` class names,  `Foundation for Sites by ZURB` in a comment
* Material Design Lite
	* HTML: `href=".*?material[\.min]?.css"` in a `link` element
	* CSS: `.mdl-*` class names, `Material Design Components` in a comment
* UIkit
	* HTML: `uikit` in the `src` value of a `script` element
	* CSS : `uk-*` class names, specifically `.uk-container`
	* JS: `UIkit` in a comment
* Tailwind
	* HTML: _no reliable signal found_
	* CSS: `--tw-*` custom properties, `sm\:*` `md\:*` `lg\:*` `xl\:*` class names, `https://tailwindcss.com` in a comment

**Comment by rviscomi** [comment]
Thanks @meyerweb this is really helpful.

For Ruby usage, are you only interested a stat like "X% of pages use Ruby" or are you looking for a breakdown of usage for each property and display value, like "X% of Ruby pages use `ruby-position`, Y% use `ruby-align`, etc"?

For library detection, it looks like all of them are supported by Wappalyzer in the [UI Frameworks category](https://www.wappalyzer.com/technologies/ui-frameworks/) plus several others. I'm not sure how closely their detections match your suggestions, but it's open source so we could find out if needed. Would it work for you if we use those readily available detections?

**Comment by meyerweb** [comment]
Yep, glad to use their data!

**Comment by meyerweb** [comment]
Are they analyzing the same data corpus we are?  If so, I’m happy to use their data.  If not, I feel like it’s worth running our own analysis, to see how well our numbers correspond to theirs.

**Comment by meyerweb** [comment]
Oh, and on Ruby, I’m mostly interested in “X% of pages use CSS Ruby”.  If that returns a surprisingly high number, by which I mean anything above single-digit percentages, I’d be interested in the followup of which properties are used how much.

**Comment by rviscomi** [comment]
We integrate Wappalyzer's detections into our testing, so it's the same corpus.

Thanks for clarifying these things. I should have the data in the next few days and I'll ping here and/or Slack when it's ready.

**Comment by rviscomi** [comment]
@svgeesus if there were any 2020 results that had both with and without the limit, this year's results correspond to the version without the limit.

**Comment by meyerweb** [comment]
@rviscomi: Perfect, thanks!

To everyone else: I drafted about a third of the chapter today, stopping here: https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit#heading=h.8ppvzpu4dlkm.  Current plan is to write the second third tomorrow, and the last third Wednesday.  I did skip writing the intros for each section (these are marked “TK intro” with an orange highlight) in order to make more headway on the analytical text.  Fact-checking and overall draft-level review notes are welcome on the parts that I’ve written.

@GeekBoySupreme, if you have any sections you’d like to tackle, particularly in the last third of the document, that would be great.  Alternatively, if you want to go through the parts I wrote and see if you want to add anything, that would also be great.

**Comment by GeekBoySupreme** [comment]
Would go through. And also pick up the last third.

**Comment by bkardell** [comment]
I'm discussing some of this with @meyerweb and since I am not listed as a reviewer or something I can't leave comments contextually on the things we're discussing.  It would be helpful to get that, I've requested access... if you want to list me as a reviewer or something, it's fine.

**Comment by meyerweb** [comment]
@rviscomi @LeaVerou There’s a huge discrepancy between this year’s custom property names analysis and last year’s.  Last year, Avada was on top with nearly 35% of all custom names.  This year, it got 3.7%.  Both analyses are (or at least appear to be) based on mobile.  It feels like either Avada didn’t get the credit it should this year, or got way too much last year.

A glance at the pivot table this year (see https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=725813203) makes me think the affiliation may have gone haywire one way or the other: Avada gets 31.48% of desktop, and 3.67% of mobile.  There is a smaller but still substantial discrepancy with Bootstrap between desktop and mobile.

FYI: I filled in all the unaffiliated custom properties with “Miscellaneous” in this year’s sheet, so the pivot table and thus the pie chart wouldn’t have a (blank) entry.  if those end up being overwritten by a new analysis run, no worries.  Let me know what you find, or what I can do to help dig into this.

**Comment by meyerweb** [comment]
@rviscomi: On the subject of the custom property names, I’m dubious of some of the affiliation assignments.  As an example, all color-like properties (`--white`, `--black`, `--red`, etc.) are credited to Bootstrap.  Bootstrap may have those names backed in, but if there’s one class of custom property names I can imagine people inventing on their own, it’s names like those.  Do the queries already check in such cases to make sure there are other, more obviously Bootstrap-ish custom properties (or other things, like a Bootstrap license statement) to be more certain of provenance?  If not, could they?

(Also, shout out to WordPress for hand-namespacing all their custom properties.  If only every project were so circumspect!)

**Comment by rviscomi** [comment]
> There’s a huge discrepancy between this year’s custom property names analysis and last year’s. Last year, Avada was on top with nearly 35% of all custom names. This year, it got 3.7%. Both analyses are (or at least appear to be) based on mobile. It feels like either Avada didn’t get the credit it should this year, or got way too much last year.

The custom property name sheet only shows the [top 1000](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2021/css/custom_property_names.sql#L41-L43) most popular values as a percentage of pages. It seems like this year there are many mobile pages with Avada that fell just below that threshold.

For example, about 50k desktop pages (0.8%) include Avada custom properties like `--color_*`. Since there are more than 1M fewer desktop pages than mobile, this makes up a larger percentage of all desktop pages. For comparison, 50k is only about 0.67% of all mobile pages, which is right at the 1000 cutoff.

This methodology doesn't really lend itself well to how the metric is being used in practice. We're manually annotating each custom property name with its corresponding tool (Avada, WordPress, Bootstrap, etc) so it would be impractical to scale this out beyond 1000 names. I think a better methodology we should explore for next year would be to automate that annotation logic in the SQL and remove the `LIMIT 1000` so that we can aggregate tool-level stats over all custom properties.

For this year, we could use the more comparable desktop data and/or include a note in the chapter explaining how our approach affected the results.

> Do the queries already check in such cases to make sure there are other, more obviously Bootstrap-ish custom properties (or other things, like a Bootstrap license statement) to be more certain of provenance? If not, could they?

This is partially answered above. Because we're manually annotating each custom property name in Sheets, we don't have the full context of what other properties are used on a given page. If we implement the annotations in SQL we'd have more control to implement a solution like the one you suggested.

**Comment by meyerweb** [comment]
Oof.  I am fairly strongly motivated to drop this analysis this year (possibly with a note as to why) and come back to it in 2022, assuming more robust analysis is created.

I would be happy to take a part in crafting that more robust analysis, to be clear.  I’m just not sure it can be put together in time for this year’s Almanac, given my delay in getting started and the complexity of the task.

**Comment by meyerweb** [comment]
> The custom property name sheet only shows the [top 1000](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2021/css/custom_property_names.sql#L41-L43) most popular values as a percentage of pages. It seems like this year there are many mobile pages with Avada that fell just below that threshold.
> 
> For example, about 50k desktop pages (0.8%) include Avada custom properties like `--color_*`. Since there are more than 1M fewer desktop pages than mobile, this makes up a larger percentage of all desktop pages. For comparison, 50k is only about 0.67% of all mobile pages, which is right at the 1000 cutoff.
> 
> This methodology doesn't really lend itself well to how the metric is being used in practice. We're manually annotating each custom property name with its corresponding tool (Avada, WordPress, Bootstrap, etc) so it would be impractical to scale this out beyond 1000 names. I think a better methodology we should explore for next year would be to automate that annotation logic in the SQL and remove the `LIMIT 1000` so that we can aggregate tool-level stats over all custom properties.
> 
> For this year, we could use the more comparable desktop data and/or include a note in the chapter explaining how our approach affected the results.

Oof. I am fairly strongly motivated to drop this analysis this year (possibly with a note as to why) and come back to it in 2022, assuming more robust analysis is created.  The only alternative I see is what you propose, switching to desktop and adding a note explaining the uncertainties in the methodology, and that is itself an argument for just taking the analysis out entirely.

I would be happy to take a part in crafting that more robust analysis, to be clear. I’m just not sure it can be put together in time for this year’s Almanac, given my delay in getting started and the likely complexity of the task.

**Comment by meyerweb** [comment]
General progress update: I got up to “CSS Mistakes” today, which means I’ll need to write that and the “Sass” section tomorrow, then start back at beginning on resolving suggestions, making my own edits, tackling anything missing, etc.  I’d hoped to finish primary drafting today, but pushing any further at this point would probably result in garbage I’d just have to replace tomorrow anyway.

So, reviewers: it’s time to really get started.  Please make minor edits as suggestions (switch your edit mode in Google Docs to “Suggesting” in the top right of the Doc), and anything major can be either a comment on the Google Doc or here in the issue.  I’d prefer comments in the Doc, but if the comment feels too huge for a sidebar comment, this is a reasonable alternative.

@GeekBoySupreme, given that I’ve gotten this far, how about you write the intro to each section as you go through the chapter?  I marked missing intros with orange and the text “TK intro”.  It would be a big help if you could do that in addition to editorial review.

**Comment by bkardell** [comment]
> manually annotating each custom property name in Sheets, we don't have the full context of what other properties are used on a given page. If we implement the annotations in SQL we'd have more control to implement a solution like the one you suggested.

I kind of agree with eric's thought to drop or at least revise this part significantly.  It might be nice to say something bland but interesting like about custom elements "X number of custom properties appear on over N pages" and then explain something like "here are the ones we feel *really* confident about" (--wp-* is pretty good/specific) but also note that there's a bunch that might or might not be other systems, and we haven't figured out a good way to count them yet.

**Comment by LeaVerou** [comment]
> @rviscomi @LeaVerou There’s a huge discrepancy between this year’s custom property names analysis and last year’s. Last year, Avada was on top with nearly 35% of all custom names. This year, it got 3.7%. Both analyses are (or at least appear to be) based on mobile. It feels like either Avada didn’t get the credit it should this year, or got way too much last year.
> 
> A glance at the pivot table this year (see [docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=725813203](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=725813203)) makes me think the affiliation may have gone haywire one way or the other: Avada gets 31.48% of desktop, and 3.67% of mobile. There is a smaller but still substantial discrepancy with Bootstrap between desktop and mobile.
> 
> FYI: I filled in all the unaffiliated custom properties with “Miscellaneous” in this year’s sheet, so the pivot table and thus the pie chart wouldn’t have a (blank) entry. if those end up being overwritten by a new analysis run, no worries. Let me know what you find, or what I can do to help dig into this.

What was the methodology this year for assigning custom properties to software? I think last year I did it manually by searching on Github. But I see Avada still has 31.48% on desktop, are you sure last year's analysis was based on mobile?

**Comment by LeaVerou** [comment]
> @rviscomi: On the subject of the custom property names, I’m dubious of some of the affiliation assignments. As an example, all color-like properties (`--white`, `--black`, `--red`, etc.) are credited to Bootstrap. Bootstrap may have those names baked in, but if there’s one class of custom property names I can imagine people inventing on their own, it’s names like those. Do the queries already check in such cases to make sure there are other, more obviously Bootstrap-ish custom properties (or other things, like a Bootstrap license statement) to be more certain of provenance? If not, could they?
> 
> (Also, shout out to WordPress for hand-namespacing all their custom properties. If only every project were so circumspect!)

Note that Bootstrap these days *does* namespace its custom properties, these ones are from old Bootstrap.
I think last year when I assigned them manually, I did take into account which groups of properties had similar usage percentages.

**Comment by rviscomi** [comment]
> I kind of agree with eric's thought to drop or at least revise this part significantly. It might be nice to say something bland but interesting like about custom elements "X number of custom properties appear on over N pages" 

+1 to dropping the software grouping if it's problematic this year.

We could still show ungrouped stats for individual custom properties if interesting, for example the top 10 custom property names:

name | desktop | mobile
-- | -- | --
--wp--style--color--link | 18.58% | 18.13%
--wp-admin-theme-color | 7.36% | 7.52%
--red | 7.40% | 7.23%
--blue | 7.39% | 7.21%
--green | 7.37% | 7.19%
--dark | 7.31% | 7.15%
--white | 7.37% | 7.07%
--primary | 7.20% | 6.93%
--secondary | 7.14% | 6.86%
--gray-dark | 7.06% | 6.82%

> What was the methodology this year for assigning custom properties to software?

@LeaVerou I tried to manually reproduce your pattern matching from 2020 on the 2021 data.

**Comment by meyerweb** [comment]
> We could still show ungrouped stats for individual custom properties if interesting, for example the top 10 custom property names:

That’s it, that’s the play.  Thanks, Rick!

**Comment by meyerweb** [comment]
@rviscomi: New question: the [Layout Methods tab](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=1349743417) returns a figure for Grid of 37% of pages.  But the next tab, [Flexbox and Grid](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=928762069), says Grid is used on 8% of pages.  I feel like I must be misunderstanding one tab or the other, but I’m not sure how to tell  or how to clarify them so that I understand what each is saying.  Can you clarify, please?

**Comment by rviscomi** [comment]
@meyerweb see [this comment thread](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit?disco=AAAAPiR6l0E)

**Comment by meyerweb** [comment]
@j9t @svgeesus @argyleink @una @estelle @LeaVerou @rachelandrew @jabranr @tomhodgins @GeekBoySupreme @bkardell **It’s time!**  Please review [the now-complete draft](https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit#heading=h.8z91yaf1dmft) at your earliest convenience.  Thank you!

As mentioned before, it’s preferred to leave comments on the Google Doc with questions/comments/concerns, unless what you need to say is too long for a Google Doc sidenote.  In that case, please comment on this issue and leave a comment in the Google Doc with the URL of your GitHub comment.

**Comment by GeekBoySupreme** [comment]
@rviscomi I pulled the data on methodology from last year's almanac and could you help modifying the numbers to fit with what we did for this year
`The data in this chapter took 121 SQL queries to produce, totaling over 10K lines of SQL including 3K lines of JavaScript functions within the SQL. This makes it the largest chapter in the Web Almanac’s history.`
and
`A lot of engineering work went into making this scale of analysis feasible. Like last year, we put all CSS code through a CSS parser, and stored the Abstract Syntax Trees (AST) for all stylesheets in the corpus, resulting in 10 TB`

**Comment by j9t** [comment]
> Please review [the now-complete draft](https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit#heading=h.8z91yaf1dmft) at your earliest convenience. Thank you!

@meyerweb, on it; what timeframe can you grant us? (I’m pretty busy but would like to contribute, in time for it to be useful.)

**Comment by meyerweb** [comment]
I believe we’re supposed to be done with editing by this Sunday (@rviscomi?), so by Thursday of this week would be ideal.  Or, if I’m wrong about the deadline or we can get a slight extension, by the end of the weekend.

**Comment by rviscomi** [comment]
Getting all reviewer feedback in by Thursday SGTM. If taking an extra day or two means having a more polished chapter, then that's a tradeoff I'd be willing to take.

Just to clarify, after the authors write the chapter and reviewers' technical feedback is incorporated, there's still a separate non-technical editing pass. We'll add all of the written-but-unedited chapters into a queue and someone from the Editors team will open a new PR with suggested edits to the markdown. If we had a bigger Editors team we would have assigned one of them to the chapter and streamlined their feedback directly in the doc.

**Comment by j9t** [comment]
Thanks for clarifying. I might only be able to provide feedback this weekend, but I’ll see what I can do.

**Comment by svgeesus** [comment]
I'm working my way through the doc.

One area that we didn't examine last year (mainly because of overlap with the Fonts chapter, so we ended up dropping all the font analysis - although it then ended up unexamined in both CSS and Fonts chapters) was the usage of font-* properties.

This year, it is at least _briefly examined_ but the **lack of usage** isn't really commented on at all

(I also think there is some mis-characterisation regarding `font-variant` and `font-stretch` in the doc at present, which I commented on there).

 I think it would be worth looking at that in a bit more detail because there is a good takeaway here for the readers this year. They are missing out on properties which are widely implemented, but simply not being used in the wild.

As an example the most common `font-variant` longhand, `font-variant-ligatures` is used on only 2.06% of mobile sites. But why? it is [widely implemented, everything but IE11](https://caniuse.com/mdn-css_properties_font-variant-ligatures) and, like all the `font-variant-*` longhands, it has a great fallback story if unsupported.

Similarly for `font-variant-numeric` at 1.75% and again, [implemented everywhere](https://caniuse.com/?search=font-variant-numeric).

`font-variant-caps` is next at 0.69% on mobile, likely because people are using the shorthand to get the most common value.

And then `font-variant-east-asian` at 0.18% on mobile (maybe next year a per-country analysis would be more informative for that property, given the predominance of European languages on the Web at present)

Is it lack of typographic interest or awareness? Is it excessive caution on using these OpenType features, if the webfont doesn't load? Or is it the need to support older browsers (older than 2016-16), when this support mainly rolled out?

Usage at a couple of percent is common enough that this isn't some brand-new feature at 0.001%, but there are also literally no downsides to using these properties so I think we could make a bit of a story about that aspect.

In terms of visualizations, a separate chart with `font-variant` and `font-variant-*` would likely be helpful. And perhaps, a graphic showing what these OpenType features can do.

**Comment by svgeesus** [comment]
Okay I have gone through the whole doc now and added comments as needed.

**Comment by j9t** [comment]
Dto., I’m done, too. Hard to find something, Eric, team 🙏 I look forward to this being published.

**Comment by meyerweb** [comment]
And it’s off to editing!  Thank you, everyone.  And if I overlooked or misidentified anyone in the contributors listing (see https://20211115t173622-dot-webalmanac.uk.r.appspot.com/en/2021/css), please accept an abject apology and an offer to reinstate you forthwith.

**Comment by shantsis** [comment]
I'm currently editing through the markdown version of the doc and I saw a great spot that could use a reference link for people to learn more

> We were unhappy to see so many IDs starting with rc-. These are part of the reCAPTCHA system, which is inaccessible to the members of the deafblind community.

Are the authors okay with linking one in? If we don't have one specifically, I think we can even just link to the accessibility chapter that covers captchas

**Comment by rviscomi** [comment]
🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! Thank you to all of the contributors who put in the time and effort to make this a great chapter.

**Comment by rviscomi** [comment]
@meyerweb @j9t @svgeesus @argyleink @una @estelle @LeaVerou @rachelandrew @jabranr @tomhodgins @thecraftysoul

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Thank you all again and I'm excited for this to launch soon!
