### ISSUE TITLE
JavaScript 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2141]
# Part I Chapter 2: JavaScript

![JavaScript illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/javascript/hero_lg.jpg)

If you're interested in contributing to the JavaScript chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @NishuGoel | @NishuGoel  | @soulcorrosion @mgechev @rviscomi @pankajparkar @tunetheweb @wallet77| @pankajparkar @max-ostapenko @rviscomi | @rviscomi @pankajparkar | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 JavaScript resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/javascript
[~google-sheets]: https://docs.google.com/spreadsheets/d/1zU9rHpI3nC6jTz3xgN6w13afW7x34xAKBh2IPH-lVxk/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/javascript.md

**Comment by rviscomi** [comment]
In #1754 I posed a question about improving our ability to analyze JS.

> The bulk of the CSS chapter's insights were made possible by the Rework library which parses the CSS into a queryable AST.
>
>What comparable options are available for JS? How can we unlock similar insights for the 2021 JavaScript chapter?

Reasking that question here to get JS chapter contributors thinking about unlocking deeper insights.

**Comment by wallet77** [comment]
Hi Almanac team,

I will be very happy to participate on this section (or maybe on the page weight and performance section too). I can help as editors or reviewer.
My background can be sum up as: mainly fullstack developer, with a real interest in performance. I now work as a backend dev + devops.
I wrote some article on medium about perf related subjects (see here: https://medium.com/@vincentvallet).
I recently published a project to analyze JS packages quality, so I guess it can help here ;)

**Comment by rviscomi** [comment]
Welcome @wallet77! I've added you as a reviewer.

**Comment by rviscomi** [comment]
Added @mgechev as a reviewer. Welcome! 👋 

@mgechev @wallet77 feel free to start brainstorming content in the [doc](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?usp=sharing) as we work on staffing the rest of the chapter. If there's anyone you'd like to see authoring this chapter, tell them about it!

**Comment by rviscomi** [comment]
📟 paging 2019 and 2020 contributors: @housseindjirdeh @rwaldron @RReverser @tkadlec @ibnesayeed @jadjoubran @ahmadawais @denar90

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by ahmadawais** [comment]
@rviscomi sure thing, I'd love to be a reviewer this year, for JavaScript and Jamstack.

**Comment by rviscomi** [comment]
@smrutiparida @Dashon-Hawkins were either of you interested in authoring/reviewing this chapter?

**Comment by ibnesayeed** [comment]
@rviscomi, I can review this chapter!

**Comment by rviscomi** [comment]
Welcome @jabranr! I'll defer to @NishuGoel as content team lead to onboard you and update the role assignments in https://github.com/HTTPArchive/almanac.httparchive.org/issues/2141#issue-868435621 as needed. For now could you request edit access to the [chapter doc](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?usp=sharing) and start brainstorming ideas for the outline?

**Comment by NishuGoel** [comment]
Welcome @jabranr. 
As yet, role assignments are as follows:-

Lead | Authors | Reviewers | Analysts | Editors | Coordinator
-- | -- | -- | -- | -- | --
@NishuGoel | @NishuGoel | @wallet77 @mgechev @soulcorrosion @ahmadawais @ibnesayeed @jabranr 

For now, let us explore resources and look for ideas for the chapter outline.

**Comment by rviscomi** [comment]
@NishuGoel FYI you should have edit access to the top comment, so that'd be the best place to keep all of the chapter metadata (contributors, milestones) up to date.

**Comment by NishuGoel** [comment]
> @NishuGoel FYI you should have edit access to the top comment, so that'd be the best place to keep all of the chapter metadata (contributors, milestones) up to date.

Don't have edit access.

**Comment by rviscomi** [comment]
Ah it looks like you haven't accepted the invitation to join the HTTP Archive team on GitHub. That will give you edit access. Try going to https://github.com/HTTPArchive/ to accept the invite.

**Comment by NishuGoel** [comment]
@pankajparkar @webtaculars Would any of you be interested to co-author the 2021 chapter?

**Comment by pankajparkar** [comment]
@NishuGoel I'll be interested to co-author. Thanks

**Comment by pankajparkar** [comment]
@NishuGoel I'm interested to co-author this. Thanks

**Comment by NishuGoel** [comment]
Welcome @pankajparkar. Could you request edit access to the chapter doc for now and we start writing down ideas for scope and outline of the chapter?

**Comment by pankajparkar** [comment]
@NishuGoel I got access to both of the docs.

**Comment by GaganSuneja** [comment]
Hi @NishuGoel I would like to contribute to this.

**Comment by gokulkrishh** [comment]
If there is extra space for a reviewer. I would like to be one.

**Comment by NishuGoel** [comment]
@denar90 @demianrenzulli @ashleyish @obto Would you be interested to join as analysts for this chapter?

**Comment by ashleyish** [comment]
My JS skills leave something to be desired, but I'm happy to weigh in on the metrics/narrative in any way that I can!

**Comment by rviscomi** [comment]
Authors/Reviewers (@NishuGoel @pankajparkar	@wallet77 @mgechev @soulcorrosion @ahmadawais @ibnesayeed @jabranr @gokulkrishh) reminder that the next milestone (completing the chapter outline) is due on June 15. Please be sure to get edit access to the [JS chapter doc](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?usp=sharing) and brainstorm what content you'd like to see in the Outline section.

@NishuGoel could you also check off "Milestone 0" in the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2141#issue-868435621) now that you have a fully staffed content team? It's good to keep this up to date with your progress so we can see how all of the chapters are doing at a glance in #2179. Thanks!

**Comment by NishuGoel** [comment]
Hi reviewers (@wallet77 @mgechev @soulcorrosion @ahmadawais @ibnesayeed @jabranr @gokulkrishh), @pankajparkar and I have started putting down items into the [JS chapter doc](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?usp=sharing), do add/edit your ideas for the chapter outline. 

We will communicate in the slack channel "javascript-2021" in the Http archive slack. Do join [here](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA).

**Comment by NishuGoel** [comment]
@rviscomi @bazzadp We are almost ready with the outline of the chapter. Will you be able to join us as an analyst if have some bandwidth?

**Comment by rviscomi** [comment]
I can help answer general questions about the dataset but unfortunately I can't commit to being an analyst. If any coauthors/reviewers are open to trying the analysis, it's possible to take on both roles.

@pankajparkar I've also resent the GitHub team invitation.

**Comment by ibnesayeed** [comment]
I have been busy lately, but now catching up. I have requested access to the docs and will provide feedback about the outline as authors put things together.

**Comment by wallet77** [comment]
Same here, a lot of work recently but I will take a look.
Sorry for the delay ;)

**Comment by rviscomi** [comment]
@NishuGoel and team, thank you for completing the chapter outline on time! 🎉 

@ashleyish @NishuGoel could both of you review the outline and make sure that anything that would depend on querying the DOM or parsing JS files is implemented as a [custom metric](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md)? I elaborated on custom metrics in [this comment thread](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit?disco=AAAAMvKpe7g) in the doc. Any new custom metrics would need to be implemented by the end of the month to be included in the test pipeline.

**Comment by max-ostapenko** [comment]
@ashleyish @NishuGoel would you need any hands for analytics tasks? I can support with custom metrics and SQL.
If yes - have you forked the legacy repo to work on custom metrics?

**Comment by NishuGoel** [comment]
@max-ostapenko That'd be really helpful! Thanks
I have been looking into this repo [here](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md)

**Comment by bryantnovas** [comment]
He Almanac team,

I'm interested in contributing as an analyst, I'm a recent data science bootcamp grad and have previous experience with html css and javascript

**Comment by pankajparkar** [comment]
@bryantnovas that's fantastic!
@NishuGoel can you please help him to get access to Almanac Javascript resources?

**Comment by rviscomi** [comment]
👋 Hi @NishuGoel @pankajparkar @ashleyish @max-ostapenko, just checking in on the chapter progress. How is the analysis coming along?

**Comment by NishuGoel** [comment]
> he chapter progress. How is the analysis coming along?

Hi @rviscomi, @pankajparkar and myself are in the middle of writing queries for the metrics here in this [Draft PR](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2323).
Would love some help from anyone who has done this before, especially the part of creating visuals in excel.

**Comment by NishuGoel** [comment]
Hi, I plan to finish writing the first draft of the chapter in the next two days, this means the chapter should be ready for editing and reviewing starting October 31.
If we target to work on editing/reviewing starting 31st and continue for a week, I am optimistic to finish the writing, editing, reviewing of the chapter by November first week end. 

@wallet77 @mgechev @soulcorrosion @ahmadawais @ibnesayeed @jabranr @gokulkrishh @pankajparkar @saketsaurabh05
Editors - I would like to understand who are available to start editing the chapter starting Oct 31? 
Reviewers - I would like to understand who are available to start editing/reviewing the chapter starting Oct 31?

Thanks.

**Comment by soulcorrosion** [comment]
Thank you @NishuGoel. I can start reading whenever you give the go.

**Comment by wallet77** [comment]
Thank you @NishuGoel , I'm ready for reading ;)

**Comment by NishuGoel** [comment]
Hi @soulcorrosion @wallet77 Here's the [draft doc](https://docs.google.com/document/d/1cAJn58dMRLY-x2LNFQBwUajylzFrY0XldjZ34LKcgTE/edit#). Please give your inputs here either as direct fixes for typos or as comments for some point that seems vague, incorrect etc. I am looking forward to completely working on edits/reviews. 

Also sending you the link on Slack channel to be able to communicate in depth, if need be.

**Comment by rviscomi** [comment]
@NishuGoel @soulcorrosion @mgechev @rviscomi @pankajparkar @tunetheweb @wallet77 @max-ostapenko

🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!

**Comment by NishuGoel** [comment]
Big thanks everyone here for pulling this off. 🚀🎉
Now, let's wait for the launch, and share away our efforts across. 

@soulcorrosion @mgechev @pankajparkar   @rviscomi @tunetheweb @shantsis @wallet77 @max-ostapenko
