### ISSUE TITLE
Markup 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2142]
# Part I Chapter 3: Markup

![Markup illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/markup/hero_lg.jpg)

If you're interested in contributing to the Markup chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @AlexLakatos | @AlexLakatos | @j9t @ibnesayeed @meyerweb @brycehowitson | @kevinfarrugia | @shantsis | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Markup resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1x7iV0Tv3hxaruwlNHdhduPpzwZc9dnqMOZW1q9nGKjI/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/markup
[~google-sheets]: https://docs.google.com/spreadsheets/d/1Ta5Ck7y3W6LCn2CeGtW7dAdLF6Lh5wV2UBQJZTz3W5Q/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/markup.md

**Comment by j9t** [comment]
Reviewer—interested and available. (Co-author if need be.)

**Comment by rviscomi** [comment]
Thanks @j9t! Added you as a reviewer.

**Comment by bazzadp** [comment]
BTW we got a suggestion from @axelboc in #1954 which might be one to consider for this chapter:

> I'd be interested to know the proportion of **explicit vs. implicit labelling of form elements**.
> 
> The presence of the `for` attribute on `label` elements would be a good first indicator. However, to go further, the query could check:
> 
> * whether both explicit and implicit labelling are used together,
> * whether the IDs referenced in the `for` attributes actually exist,
> * what kind of [labelable form elements](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable) are more likely to be explicitly vs implicitly labelled (or not labelled at all even?) - e.g. perhaps checkbox and radio buttons are more likely to be implicitly labelled for styling purposes?
> 
> Explicit vs. implicit labelling vs. both

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @bkardell @zcorpan @tomhodgins @matthewp @catalinred @iandevlin @matuzo @Tiggerito

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by Tiggerito** [comment]
I don't have the time to give this year, but I could support a new Analyst in getting up to speed.

**Comment by rviscomi** [comment]
@meyerweb were you interested in being an author or reviewer of this chapter? Also pinged you in the [CSS](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140) chapter, LMK if you'd be interested in either/both.

**Comment by rviscomi** [comment]
@jabranr were you interested in reviewing this chapter? (or JS/CSS)?

**Comment by ibnesayeed** [comment]
I can review this chapter!

**Comment by matuzo** [comment]
I’d love to contribute again, but unfortunately I don’t have the time this year.

**Comment by jabranr** [comment]
> @jabranr were you interested in reviewing this chapter? (or JS/CSS)?

@rviscomi I can go for JS/CSS ones.

**Comment by tomhodgins** [comment]
I'm curious/willing to help with a CSS chapter in whatever way helps!

Cheers,
Tommy

**Comment by meyerweb** [comment]
Sorry for the delay.  I can definitely commit to being a reviewer for Markup as well as CSS.  Still running the idea of authoring past my team at work.

**Comment by j9t** [comment]
Hi @rviscomi—I’d love to, alas I won’t have the bandwidth this year. I’m happy to go beyond reviewing though, to assist the chapter lead as much as I can.

**Comment by brycehowitson** [comment]
I'd help as a reviewer or contribute where I can (Markup or CSS). Though I hesitate to take a huge role as I'm new to the process/time commitments.

**Comment by rviscomi** [comment]
Welcome @brycehowitson! I've added you as a reviewer for the Markup chapter. As we continue looking for a lead for the team, you can get started by requesting edit access to the [draft doc](https://docs.google.com/document/d/1x7iV0Tv3hxaruwlNHdhduPpzwZc9dnqMOZW1q9nGKjI/edit?usp=sharing) and adding your ideas.

**Comment by bazzadp** [comment]
And interest @matuzo ?

**Comment by AlexLakatos** [comment]
Just saw the tweet, I'd be happy to take on the author slot.

**Comment by rviscomi** [comment]
@AlexLakatos thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) to **find an analyst** and add any additional coauthors/reviewers as needed
- Due **June 15**: Complete [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) to **brainstorm content** ideas in the [doc][~google-doc] (you'll need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2142#issue-868435668
[~google-doc]: https://docs.google.com/document/d/1x7iV0Tv3hxaruwlNHdhduPpzwZc9dnqMOZW1q9nGKjI/edit?usp=sharing

**Comment by shantsis** [comment]
Any room for an editor in this chapter? 🙂

**Comment by rviscomi** [comment]
Absolutely, thanks for your interest @shantsis! I'll add your name to the Editor role.

FYI editing won't start until after Milestone 3 has been completed and the [chapter is drafted](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content). Do you have any interest in getting involved sooner during the content planning going on now? If so I can also add you as a reviewer. (The difference between reviewer and editor is that reviewers are involved in content planning and give technical feedback while editors focus more on the quality of writing and give non-technical feedback)

**Comment by shantsis** [comment]
> Absolutely, thanks for your interest @shantsis! I'll add your name to the Editor role.
> 
> FYI editing won't start until after Milestone 3 has been completed and the [chapter is drafted](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content). Do you have any interest in getting involved sooner during the content planning going on now? If so I can also add you as a reviewer. (The difference between reviewer and editor is that reviewers are involved in content planning and give technical feedback while editors focus more on the quality of writing and give non-technical feedback)

I’m good for editing thanks

**Comment by AlexLakatos** [comment]
> @AlexLakatos thanks for your interest in authoring this chapter! 
Thanks!

> Next steps for this chapter are:
> 
>     * Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) to **find an analyst** and add any additional coauthors/reviewers as needed
It looks like we've got quite a few reviewers, which is great! But this is an awfully short deadline, how / where do I find a willing analyst? Do I comment in #2193 and hope for the best?

**Comment by matuzo** [comment]
> Any interest @matuzo ?

Unfortunately I wouldn't find enough time this year to do the job properly, but maybe next year. :)

**Comment by kevinfarrugia** [comment]
Hi all. I can join the chapter as analyst. This is my first time contributing so I'll be learning along the way. I have gone through last year's queries for the Markup chapter and I expect we would be reusing most of these this year too. Are there any custom metrics which you would like to include?

**Comment by rviscomi** [comment]
Great news, thanks for stepping up @kevinfarrugia! Feel free to join the #web-almanac-analysts channel on Slack to chat with other analysts and get help as needed. @paulcalvano leads the Analysts team and can get you set up with dataset access and answer any other questions.

@AlexLakatos that takes care of Milestone 0, you can go ahead and check that off now.

**Comment by Tiggerito** [comment]
@kevinfarrugia I was last years analyst. I'm happy to answer any questions you have. It was also my first time last year.

**Comment by AlexLakatos** [comment]
Amazing! Thanks @kevinfarrugia for stepping in! @Tiggerito appreciate the help!

**Comment by kevinfarrugia** [comment]
@AlexLakatos do you need any input from my end ahead of the deadline for the custom metrics please?

**Comment by rviscomi** [comment]
@AlexLakatos	@j9t @ibnesayeed @meyerweb @brycehowitson	@kevinfarrugia to Kevin's point, the outline in the [chapter doc](https://docs.google.com/document/d/1x7iV0Tv3hxaruwlNHdhduPpzwZc9dnqMOZW1q9nGKjI/edit?usp=sharing) hasn't been started yet. It's up to the authors/reviewers to brainstorm topics to discuss in the chapter, which will give analysts (Kevin) guidance for what data needs to be prepared. Everyone should have edit access to the doc (request it in the doc if not) so you can start adding your thoughts/suggestions. For reference here was [last year's Markup chapter doc](https://docs.google.com/document/d/1m1YvDqWgZfqmcmAEkCnXncIJwsM1QCu6Rv7aPWjG1Ms/edit?usp=sharing).

The deadline for completing the outline is **June 15** so that there's time to make any changes to the test infrastructure. Missing this deadline may mean that you won't have access to new metrics.

**Comment by j9t** [comment]
If it’s helpful, last year I took [the previous year’s structure](https://almanac.httparchive.org/en/2019/markup) to build the chapter outline, to complement it by input by the group. That worked well to be fast but also make sure we didn’t miss anything major.

**Comment by ibnesayeed** [comment]
I have been busy lately, but now catching up. I have requested access to the docs and will provide feedback about the outline as authors put things together.

**Comment by tunetheweb** [comment]
Interesting discussion here you might want to consider as incorrect markup: https://twitter.com/therealnooshu/status/1404356341297303555?s=21

**Comment by AlexLakatos** [comment]
@j9t @ibnesayeed @meyerweb @brycehowitson @kevinfarrugia @shantsis @rviscomi: I've created a tentative outline in the working doc, I'd love to get your feedback on it. It's retained most of the sections from last year, with a few extras sprinkled in. I'm conscious of not stepping too much in other chapters territory, so some of those new sections might only get a shallow mention.

I'd also love if we could show most of the data in there compared to 2019 and 2020 where it makes sense, I'd love to know which of those metrics we don't have to structure the sections accordingly (probably all the new ones).

**Comment by rviscomi** [comment]
Looks good thanks @AlexLakatos. Please check off Milestone 1 [above](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2142#issue-868435668) when you're feeling comfortable with the outline.

@kevinfarrugia there may be new topics in the outline that depend on custom metrics, so please give it a close look to see if there's anything we need to add to the test pipeline. Refer to the 2020 chapter's [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/markup.js) to see what's currently implemented and don't be afraid to take @Tiggerito up on his [offer](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2142#issuecomment-852540498) to answer any questions!

**Comment by kevinfarrugia** [comment]
I will be going through the outline and reviewing the custom metrics at the end of this week or the start of the next. Will let you know if I have any queries. Thanks

**Comment by kevinfarrugia** [comment]
@AlexLakatos I have tagged you on the Google Doc (sorry for the spam) as there are a number of pending queries from my end please.

**Comment by AlexLakatos** [comment]
I think I got to all of them now, let me know if you need more info!

**Comment by j9t** [comment]
@AlexLakatos, not to give you a feeling you’ve been abandoned—anything our group of reviewers can do or help with at the moment?

**Comment by kevinfarrugia** [comment]
An update from my end too that I'm going through the queries and will have some updates in the next few days.

**Comment by kevinfarrugia** [comment]
I have started putting some of the data in a [Google Sheet](https://docs.google.com/spreadsheets/d/1cg621HiQVwgNSsNpSM7w3s4ekbp31WWbn9TULSkToSA/edit?usp=sharing) and will be updating the PR once I clean up some unused queries. Early feedback is welcome.

**Comment by rviscomi** [comment]
Thanks for the update @kevinfarrugia! @AlexLakatos have you had a chance to start reviewing the results?

**Comment by AlexLakatos** [comment]
Not yet, but I think I'll get to them this week.

**Comment by kevinfarrugia** [comment]
Hi @AlexLakatos how's it coming along? Do you need my input on any of the queries or results?

**Comment by AlexLakatos** [comment]
@kevinfarrugia It's coming slower than I anticipated, but I hope to finish this weekend. Most queries were straightforward. I could use a second pair of eyes on the "Compression" section. I used filtering on the "content_encoding" sheet to come up with the data, I could use someone double-checking if that's the right way to do it.

**Comment by kevinfarrugia** [comment]
I created a pivot table for the `content_encoding` sheet and a bar chart. I'm not sure if that's what you want to show. Let me know if that helps you.

content_encoding | desktop | mobile
-- | -- | --
gzip | 62.85% | 63.84%
br | 21.75% | 21.93%
  | 15.26% | 14.11%
deflate | 0.10% | 0.10%

![Uploading Content encoding.png…]()

**Comment by AlexLakatos** [comment]
@kevinfarrugia That's better than what I had in mind, thanks!

**Comment by rviscomi** [comment]
@AlexLakatos how's it going? Looks like there's still a lot of writing to go. Are you mostly blocked on the data visualization part? Let me know if I can help with that.

Given the short time remaining it's highly likely that this chapter will not be fully written/reviewed/edited in time for the November 15 milestone, so let's start thinking about a more realistic timeline. @AlexLakatos can you commit to having the first draft ready for review by the 15th? We can give the reviewers a week to submit their feedback and get it resolved. That leaves only a few days to get the markdown into shape before publication. I can't guarantee that we'll have time for a formal editing pass before that though, so it may have the scarlet "unedited" badge initially, but the most important thing is to get the chapter out there for the rush of traffic after launch. So the timeline would be:

November 15: @AlexLakatos finishes the first draft (ideally straight to markdown to save time)
November 22: @j9t @ibnesayeed @meyerweb @brycehowitson finish their review
November 24: @AlexLakatos resolves all reviewer feedback and submits the markdown PR
(Editing if possible)
December 1: Launch

**Comment by AlexLakatos** [comment]
I think we can make that happen, I will try to make it happen faster than the 15th, but I don't want to over-commit again, so let's keep it the 15th. The big blocker is not visualization, though I could use help with those, I haven't figured out how to generate those yet. I'll leave comments in the doc for them.

**Comment by rviscomi** [comment]
Hi @AlexLakatos, have you been able to make any progress on the draft this week? Do you still think you can get it written by Monday?

**Comment by rviscomi** [comment]
@AlexLakatos could you give us a status update?

**Comment by AlexLakatos** [comment]
Made a decent dent into it, there are two chapters left, which I hope to complete today. In the meantime, I think we can start reviewing what's there.

**Comment by AlexLakatos** [comment]
4680 words later, I'd say the first draft of the Markup chapter is done. Happy reviewing! I'll run Grammarly on it in the morning. @j9t @ibnesayeed @meyerweb @brycehowitson, I'd love it if you took advantage of the suggestions feature of GDocs while reviewing! Let me know if you have any questions during the review.

Also, if anyone identifies an opportunity to swap some of the tables for charts, please go for it, I do feel like I've favored tables for some reason.

**Comment by j9t** [comment]
On it. Aware of the urgency, probably need this weekend to give feedback.

**Comment by tunetheweb** [comment]
I've made lots of suggestions for charts. I think they are much better (and colourful!) than table after table and table and more consistent with other chapters.

We also should move away from giving absolute numbers. Saying an element if used 3,055,068 times is meaningless without the context (which a % gives) and also makes it really difficult to compare year on year numbers since the number of websites we crawl changes continually (it's based on usage in previous months so is constantly changing - usually increasing!).

I've also rerun a lot of your queries and updated the sheets. Many of the queries were ordering by client, and then cutting off at 100 rows or similar, meaning you only got the `desktop` data back as the `mobile` results were outside that 100 limit. I've switched the queries to order by percentage descending to avoid this. @kevinfarrugia FYI

**Comment by AlexLakatos** [comment]
Thank you @tunetheweb for the charts, they are great!

**Comment by j9t** [comment]
Finished reviewing and [providing feedback](https://docs.google.com/document/d/1x7iV0Tv3hxaruwlNHdhduPpzwZc9dnqMOZW1q9nGKjI/edit). Overall nice work, exciting to see this!

**Comment by AlexLakatos** [comment]
I've finished going through the reviews, thank you all for the comments and suggestions. There are a handful of discussions that could benefit from a response, would appreciate if we could wrap those up.

**Comment by rviscomi** [comment]
@AlexLakatos @j9t @ibnesayeed @meyerweb @brycehowitson @bkardell @shantsis I see there are still some open comments in the doc. Could you all take a look to see if you can resolve any of them? (some are for reviewers, and others for the author)

We should get this converted to markdown ASAP to get merged in time for launch, hopefully with enough time to give it a copyediting pass.
