### ISSUE TITLE
Fonts 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2143]
# Part I Chapter 5: Fonts

![Fonts illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/fonts/hero_lg.jpg)

If you're interested in contributing to the Fonts chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @jpamental | @jpamental | @rsheeter @davelab6 @svgeesus | @jessthebp @konfirmed | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [ ] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Fonts resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/18bIMkKA48CWGTIrQAhoFGFdbTf2iQgQRkhNwOJlENpM/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/fonts
[~google-sheets]: https://docs.google.com/spreadsheets/d/1LtahQmT53kj_Z2lMKAr5kSWzskwIe9SbbmIPCH0j_n4/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/fonts.md

**Comment by rsheeter** [comment]
Interested, given time constraints probably as reviewer

**Comment by rviscomi** [comment]
Excited to have you both involved again this year @rsheeter @davelab6!

**Comment by jpamental** [comment]
I'd be happy to author again (I'll be more prompt, I promise!) or reviewer (or editor for that matter0

**Comment by rviscomi** [comment]
Thanks @jpamental it's great to have you back! I'll tentatively add you as a reviewer per #2165 to leave room for new authors if interested.

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @zachleat @hyperpress @AymenLoukil @tjmonsi @raphlinus @malchata @RoelN @svgeesus @AbbyTsai

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by jessthebp** [comment]
Hi! I'd love to contribute to this chapter in whichever way I can.

**Comment by rviscomi** [comment]
Thanks @jessthebp! Do you have bandwidth to be the analyst for this chapter as well? Those are in short supply.

**Comment by jessthebp** [comment]
@rviscomi I have that bandwidth!

**Comment by malchata** [comment]
Hey, @rviscomi. Thanks for checking in, but I won't be able to this year, as I'm releasing a book this year and primarily focusing on getting that done. But I'd love to be a part of either this or any other chapters you think I'd be handy on next year!

**Comment by rviscomi** [comment]
@malchata Totally understand and congratulations on your book! We'll ping you again next year.

**Comment by svgeesus** [comment]
Happy to be a reviewer

**Comment by rviscomi** [comment]
@jpamental are you able to edit the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2143#issue-868435706) to check off the 0th milestone?

**Comment by jpamental** [comment]
Apparently I can! Done :)

**Comment by rviscomi** [comment]
Great thanks! I'll defer to you to keep that metadata in sync with any completed milestones or contributor changes. It's helpful for us to see chapter progress at a glance in #2179.

**Comment by RoelN** [comment]
I'm interested in helping out as well, as reviewer or general helper-outer.

**Comment by rviscomi** [comment]
👋  Great to have you back @RoelN! I'll defer to @jpamental to get you onboarded.

**Comment by bazzadp** [comment]
Having just published [an article on it](https://www.smashingmagazine.com/2021/05/reduce-font-loading-impact-css-descriptors/), I'd be interested in use of the new font-face descriptors (aka f-mods).

**Comment by rviscomi** [comment]
📟  Attn content team (@jpamental @rsheeter @davelab6 @svgeesus @jessthebp) reminder that the next milestone ([complete the chapter outline](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)) is due by **June 15**. Please be sure to request edit access to the [Fonts chapter doc](https://docs.google.com/document/d/18bIMkKA48CWGTIrQAhoFGFdbTf2iQgQRkhNwOJlENpM/edit?usp=sharing) and brainstorm the content you want to see this year. Completing the outline on time will ensure that any new runtime telemetry needed by the chapter is in place before the July 1 crawl begins.

**Comment by svgeesus** [comment]
> Having just published an article on it, I'd be interested in use of the new font-face descriptors (aka f-mods).

I'm expecting usage to be small, but examining that usage early on will be helpful and might inform future development of CSS Fonts 5, too. So it is worth doing (if we can see _how_ people are using it, rather than just counting it)

**Comment by rviscomi** [comment]
Hi @jpamental, the due date for the chapter outline is June 15 and it doesn't look like it's been started yet.

I'd suggest using the [2020 outline](https://docs.google.com/document/d/15-rYqS-FqKWD0_32LdajEg0tD1Tm0KzgTYyLF2pQK8M/edit?usp=sharing) and published [Table of Contents](https://almanac.httparchive.org/en/2020/fonts) as a starting point and adding/removing topics as you see fit. Let me know if you have any questions or concerns about meeting the next milestone.

**Comment by rviscomi** [comment]
Hey @jpamental, could you give us an update on the chapter outline? It's good to see some ideas in there, but I'm not sure if you're still working on it. If it's complete, you can check off Milestone 1 [above](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2143#issue-868435706), otherwise please let us know your ETA.

**Comment by tunetheweb** [comment]
Just read this, which might be of interest to this chapter: https://dribbble.com/stories/2021/04/26/web-design-data-fonts

If any interest in continuing this research as part of this team then let us know @tianhuil !

**Comment by rviscomi** [comment]
⚠️ @jpamental is there anything we can do to help get this chapter back on track and complete the outline? The outline determines what metrics are needed, and any new custom runtime metrics would need to be implemented now to be in before the July crawl starts.

**Comment by svgeesus** [comment]
@rviscomi in the absence of any update I suggest running the same metrics as last year which will at minimum allow commenting on any changes.

**Comment by rviscomi** [comment]
⛔ Milestones 1 and 2 are still unchecked so I'm very worried that this chapter has fallen too far behind to be able to launch on time. All other chapters are currently on Milestone 3 (analyzing the data) but this chapter has been blocked on the outline.

@svgeesus's suggestion to rerun 2020 queries is better than having no data, but we need to be sure that @jpamental still has the interest/availability to commit to authoring the chapter. I completely understand that other things come up and commitments change, we just need to know if that's the case ASAP so we can adapt as needed.

I see three possible paths:

1. @jpamental finalizes the outline (M1) this week. @jessthebp is unblocked to draft the metrics PR (M2) next week. @jessthebp is then able to write/run the queries (M3), which is due September 30.
2. If @jpamental is unable to commit to authoring, and another contributor is willing/able to take the author role, we reassign ownership of the chapter and proceed according to (1) above.
3. If no one is able to commit to authoring, or M1/M2 are incomplete by September 1, we have no other choice but to close the chapter.

Does that sound fair? And @jessthebp are you still able to get the analysis done on a shortened timeline? Open to any other ideas to get the chapter back on track.

**Comment by jpamental** [comment]
Hi there - I'm so sorry. I thought I had finalized the outline a while ago, but just went back to make a couple of tweaks and have checked it off above. I am definitely willing and able to continue as author.

@jessthebp if you have any questions about the outline please let me know and I'll get back to you right away.

Here's a link to the doc: https://docs.google.com/document/d/18bIMkKA48CWGTIrQAhoFGFdbTf2iQgQRkhNwOJlENpM/edit

**Comment by konfirmed** [comment]
Hi, I'll like to help here if needed

**Comment by rviscomi** [comment]
👋 Hi @jpamental @jessthebp, just checking in on the chapter progress. How is the analysis coming along?

**Comment by jpamental** [comment]
I've been waiting to hear from @jessthebp on the analysis, but if I missed stuff becoming available I'll dive in!

@konfirmed let me know what you'd be interested in doing! I think at this point we're waiting on data analysis before I can jump in and start writing. Help in any area would be welcome!

**Comment by konfirmed** [comment]
@jpamental I am interested in reviewing but can help with data analysis if that's the current hold up.

**Comment by jessthebp** [comment]
Hi, @jpamental + @konfirmed -- I'm working on the analysis this week. I'll keep you updated, let me know what else I can do.

**Comment by rviscomi** [comment]
⚠️ Hey @jpamental the work for Milestone 3 is coming up on the deadline for Milestone 4, which puts this chapter at high risk of being unable to publish on time. Are you able to coordinate with your team to get the chapter back on track ASAP?

**Comment by rviscomi** [comment]
⛔ @jpamental this chapter desperately needs your attention in order to publish on time. If you're unable to make progress on the draft in the next few days we may need to consider closing this chapter :(

**Comment by rviscomi** [comment]
Apologies to everyone looking forward to the Fonts chapter this year but unfortunately it doesn't seem feasible to publish it at this point. Thank you to everyone who signed up to contribute and put effort into it, I'm hopeful that we'll be able to carry some of that enthusiasm over into next year's chapter.

**Comment by svgeesus** [comment]
Oh, @rviscomi  sad, but understandable given the lack of any content.

Thanks to the Analysts @jessthebp @konfirmed for their work, and hopefully this year's result sheet is helpful as a point of comparison for next year.

Probably best to recruit a couple of interested and motivated 2022 editors from the typographic community, sooner rather than later.

I'm interested in at least reviewing next year, and maybe co-editing if I am confident of being able to commit the time.

**Comment by rviscomi** [comment]
+1 thank you for that @svgeesus.

I'd encourage anyone interested in participating in the 2022 Web Almanac to fill out [this form](https://forms.gle/j2f6tFojB8ZkWvRv8) so that we can notify you when we kick off the planning stage next year. Leave a note about your interest in fonts (or any other chapter) and we'll tag you in the relevant issues.

**Comment by tunetheweb** [comment]
Wasn't aware you were waiting on that. All the queries were written but see now they weren't run. They have been now and available in the chapter sheet: https://docs.google.com/spreadsheets/d/1LtahQmT53kj_Z2lMKAr5kSWzskwIe9SbbmIPCH0j_n4/
