### ISSUE TITLE
Third Parties 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2145]
# Part I Chapter 8: Third Parties

![Third Parties illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/third-parties/hero_lg.jpg)

If you're interested in contributing to the Third Parties chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | ---- |
| @tunetheweb | @tunetheweb | @patrickhulce @housseindjirdeh @simonhearne @andydavies @csswizardry | @tunetheweb | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Third Parties resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/164HhV76iVT2qVfFY2kzyr44eIcGAw3fWqNTbuoRfRvE/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/third-parties
[~google-sheets]: https://docs.google.com/spreadsheets/d/1tf4RMF8SYr6he9tbqt61yuFJ_QK-F-i7XPxaPkpKSDI/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/third-parties.md

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @patrickhulce @simonhearne @flowlabs @jasti @zeman @tammyeverts @jzyang @exterkamp @max-ostapenko

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by patrickhulce** [comment]
I'm happy to review :)

**Comment by max-ostapenko** [comment]
Add me as an analyst, please :)

**Comment by rviscomi** [comment]
⚠️ Still looking for more contributors to make this chapter viable, specifically authors. If we're unable to staff the chapter by May 31 we may have to close it and focus our efforts on other chapters.

**Comment by peerside** [comment]
I'm happy to author if no one else steps up. I'm conscious I don't have the same domain knowledge or experience of the people tagged above but I do have bandwidth and interest.

**Comment by rviscomi** [comment]
@peerside thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

There's also a `#web-almanac-third-parties` channel on [Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) which you can use to coordinate with your team, if you'd like.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—you can check this off now since you've already got at least one author, reviewer, and analyst ✨
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2145#issue-868435771
[~google-doc]: https://docs.google.com/document/d/164HhV76iVT2qVfFY2kzyr44eIcGAw3fWqNTbuoRfRvE/edit?usp=sharing

**Comment by rviscomi** [comment]
@peerside @patrickhulce @max-ostapenko reminder that the next milestone ([complete the chapter outline](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)) is due on **June 15**. Please request edit access to the [Third Parties chapter doc](https://docs.google.com/document/d/164HhV76iVT2qVfFY2kzyr44eIcGAw3fWqNTbuoRfRvE/edit?usp=sharing) and begin brainstorming what content you'd like to include in this year's chapter. Completing this on time will ensure that any changes to the testing are in place before the crawl begins on July 1.

@peerside could you also update the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2145#issue-868435771) to check off Milestone 0 now that your content team is fully staffed (author, reviewer, and analyst)? Keeping your chapter metadata up to date helps us track chapter progress at a glance in #2179 🙏

**Comment by rviscomi** [comment]
Hi @peerside I didn't see any progress in the doc yet so I wanted to give you a nudge. The outline is due June 15. Please also take a minute to check off Milestone 0. Thanks and let me know if you've got any questions.

**Comment by rviscomi** [comment]
⚠️  @peerside let us know ASAP if you're unable to commit to authoring this chapter. No worries if that's the case, but we would need to make alternate plans immediately if so.

If you're still interested and available, please see my previous messages about completing the chapter outline in the doc. June 15 is the deadline to stay on schedule, so it'd be great to see some signs of progress on it before the end of the week.

**Comment by rviscomi** [comment]
Today is the due date for Milestone 1 and given that no progress has been made nor have I been successful in my attempts to reach the team lead here or via Twitter DMs, I'm going to take that to mean that @peerside is no longer able to commit to the chapter. No hard feelings, I completely understand that higher priority things come up, and I hope all is well.

Unfortunately, my only option is to close the chapter, unless anyone else would like to step up and take the lead/author role. If the chapter does make a comeback, note that it may be too late to add any new metrics beyond whatever is already available in the pipeline. Ping this thread if you're interested and I'd be happy to open it back up.

@patrickhulce @max-ostapenko very sorry about this, but I hope you'd consider joining another chapter. You can browse the list of chapters that are still looking for [reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%3A+reviewers%22) and [analysts](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%3A+analysts%22).

**Comment by tunetheweb** [comment]
I'd like to bring this chapter back and am prepared to do most of the work to do that! Third-parties are a massive part of the web and think it would be a real shame not to at least update the stats from last year. Also have a couple of ideas on new stats.

I've [filled out the chapter outline](https://docs.google.com/document/d/164HhV76iVT2qVfFY2kzyr44eIcGAw3fWqNTbuoRfRvE/edit) (mostly the same as 2020 with a few additions), opened a [draft Pull Request for the queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2355), and run all but one of the 2020 queries (updated to 2021) into the [results sheet](https://docs.google.com/spreadsheets/d/1tf4RMF8SYr6he9tbqt61yuFJ_QK-F-i7XPxaPkpKSDI/edit?usp=sharing). Which I think brings us almost up to speed and certainly only a similar footing as many other chapters. Hope to have the queries finished this week and the draft started.

@max-ostapenko you expressed an interest in being the analyst. Still interested, as have a few more queries to write, or got enough on your plate with the other chapters?

@patrickhulce you still willing to be a reviewer here?
@simonhearne any chance I can sign you up to being a reviewer?
@andydavies understand you were gonna talk about this at PerfNow before it was cancelled so any chance I can sign you up as a reviewer? At very least it'll give you some stuff to quote when you eventually do give that talk!

Anyone else interested too let me know, and open for co-authors if anyone wants to do a bit of writing too!

**Comment by tunetheweb** [comment]
All queries run and available in the sheet: https://docs.google.com/spreadsheets/d/1tf4RMF8SYr6he9tbqt61yuFJ_QK-F-i7XPxaPkpKSDI/

**Comment by rviscomi** [comment]
@tunetheweb @patrickhulce @housseindjirdeh @simonhearne @andydavies @csswizardry

Thank you all for your hard work getting this chapter over the finish line in time for the pre-release! Congratulations on finishing the chapter, and I'm excited to see us launch the rest of the chapters along side it on Wednesday 🎉

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏
