### ISSUE TITLE
Resource Hints 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2158]
# Part IV Chapter 21: Resource Hints

![Resource Hints illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/resource-hints/hero_lg.jpg)

If you're interested in contributing to the Resource Hints chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @kevinfarrugia | @kevinfarrugia | @siakaramalegos @Zizzamia @samarpanda | @Nithanaroy | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Resource Hints resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1zIKdkS65X9u3rGZOn1kG0rk9YveFb0zhdORBFOoIgQQ/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/resource-hints
[~google-sheets]: https://docs.google.com/spreadsheets/d/1Mw6TjkIClRtlZPHbij5corOZbaSUp-vgTVq3Ig18IwQ/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/resource-hints.md

**Comment by Nithanaroy** [comment]
I would like to be an analyst

**Comment by rviscomi** [comment]
Great thanks @Nithanaroy! I've added you to the team.

**Comment by siakaramalegos** [comment]
Hi, I'd be interested in being an author. I write and speak on performance as well as perform contract work for various companies on performance. You can learn more about me on my website (including articles, talks, and workshops): https://sia.codes/

If I'm not chosen as an author on this or any other page, I'm happy to be a reviewer or editor. Thanks for your consideration.

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @khempenius @andydavies @addyosmani @bazzadp @yoavweiss @Zizzamia @notwillk @giopunt @jessnicolet @pmeenan @mgechev

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by rviscomi** [comment]
@demianrenzulli were you also interested in being a reviewer of the Resource Hints chapter?

**Comment by siakaramalegos** [comment]
Just wanted to note that I'm authoring a different chapter so I'll won't be authoring this one (please volunteer to author!). @rviscomi , I can still review if it's still needed and the workload is timed ok with authoring.

**Comment by rviscomi** [comment]
Sounds great, thanks @siakaramalegos!

**Comment by Zizzamia** [comment]
Oh nice, feel free to add me as Reviewer. Happy to help :-)

**Comment by samarpanda** [comment]
Can i join as a reviewer?

**Comment by rviscomi** [comment]
Absolutely, welcome @samarpanda!

⚠️ Note that we're still looking for more contributors to make this chapter viable, specifically authors. If we're unable to staff the chapter by May 31 we may have to close it and focus our efforts on other chapters. It does have some overlap with Performance, so we may be able to integrate this topic if @siakaramalegos is amenable.

One suggestion for you all that may help draw in new contributors would be to post to your professional networks that we're still looking for someone experienced with resource hints to author this chapter and to reply to this issue if interested.

**Comment by siakaramalegos** [comment]
@rviscomi if needed, I can make it work. Would still love to find an author for this chapter though. Will post again!

**Comment by rviscomi** [comment]
I spoke with @kevinfarrugia offline and they volunteered to author this.

@kevinfarrugia thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—you can check this off now since you've already got at least one author, reviewer, and analyst ✨ 
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2158#issue-868436290
[~google-doc]: https://docs.google.com/document/d/1zIKdkS65X9u3rGZOn1kG0rk9YveFb0zhdORBFOoIgQQ/edit?usp=sharing

**Comment by kevinfarrugia** [comment]
Hey everyone, thanks for volunteering to contribute to the Resource Hints chapter team! I created a channel in the [HTTP Archive Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) for this chapter - please join in for chat/discussions.

### TODO
@siakaramalegos @Zizzamia @samarpanda @Nithanaroy 
- Join the Slack channel `#web-almanac-resource-hints`
- Request edit access to the [Google doc]
- Please add your name and email address to the Content Team portion of the draft Google doc.

**If you're new:**
- You can find detailed descriptions of each role in the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) article in the wiki.
- Last year's methodology: https://almanac.httparchive.org/en/2020/methodology

**Comment by kevinfarrugia** [comment]
@rviscomi are you able to send me a link of last year's Google Doc please?

**Comment by bazzadp** [comment]
> @rviscomi are you able to send me a link of last year's Google Doc please?

Here's the chapter tracker from last year: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989 with all the links.

**Comment by pmeenan** [comment]
@bazzadp It should be possible. We report the actual console log as well as the audits/interventions reports but if you happen to have an example page where it fires I can check and see where it ends up.

**Comment by kevinfarrugia** [comment]
I'll prepare a couple of sample pages with the errors.

**Comment by pmeenan** [comment]
Looks like the HAR files didn't used to report the console log output.  I just added it so it should be available with the June crawl.  I see regular log messages and intervention messages showing up but we should still test these specific cases just to be sure.

This is what it looks like:

```json
"_consoleLog": [
    {
        "source": "intervention",
        "level": "info",
        "text": "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/baloothambi2/v2/cY9cfjeOW0NHpmOQXranrbDyu7hADpI.woff2",
        "timestamp": 1621947411946.331,
        "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
        "lineNumber": 20,
        "stackTrace": {
            "callFrames": [
                {
                    "functionName": "k",
                    "scriptId": "6",
                    "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
                    "lineNumber": 20,
                    "columnNumber": 1423
                }
            ]
        }
    },
    {
        "source": "intervention",
        "level": "info",
        "text": "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/baloothambi2/v2/cY9ffjeOW0NHpmOQXranrbDyu7CzLYe-RB4.woff2",
        "timestamp": 1621947411947.563,
        "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
        "lineNumber": 20,
        "stackTrace": {
            "callFrames": [
                {
                    "functionName": "k",
                    "scriptId": "6",
                    "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
                    "lineNumber": 20,
                    "columnNumber": 1423
                }
            ]
        }
    },
    {
        "source": "intervention",
        "level": "info",
        "text": "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/baloothambi2/v2/cY9ffjeOW0NHpmOQXranrbDyu7CfKoe-RB4.woff2",
        "timestamp": 1621947411948.13,
        "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
        "lineNumber": 20,
        "stackTrace": {
            "callFrames": [
                {
                    "functionName": "k",
                    "scriptId": "6",
                    "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
                    "lineNumber": 20,
                    "columnNumber": 1423
                }
            ]
        }
    },
    {
        "source": "intervention",
        "level": "info",
        "text": "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/baloothambi2/v2/cY9ffjeOW0NHpmOQXranrbDyu7D7K4e-RB4.woff2",
        "timestamp": 1621947411948.3818,
        "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
        "lineNumber": 20,
        "stackTrace": {
            "callFrames": [
                {
                    "functionName": "k",
                    "scriptId": "6",
                    "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
                    "lineNumber": 20,
                    "columnNumber": 1423
                }
            ]
        }
    },
    {
        "source": "intervention",
        "level": "info",
        "text": "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/baloothambi2/v2/cY9ffjeOW0NHpmOQXranrbDyu7DnKIe-RB4.woff2",
        "timestamp": 1621947411948.7568,
        "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
        "lineNumber": 20,
        "stackTrace": {
            "callFrames": [
                {
                    "functionName": "k",
                    "scriptId": "6",
                    "url": "https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js",
                    "lineNumber": 20,
                    "columnNumber": 1423
                }
            ]
        }
    }
]
```

**Comment by pmeenan** [comment]
For debugging purposes, if you click on the screenshot in the WebPageTest results, below the screenshot it displays the console log messages: https://dev.webpagetest.org/result/210525_ZiDcBA_c3fe4286cf3f4082d652b5fb211fb6d9/1/screen_shot/#step_1

**Comment by bazzadp** [comment]
Awesome - thanks @pmeenan !

**Comment by kevinfarrugia** [comment]
Perfect. Thank you @pmeenan . 

Demo URLs:
- https://kevinfarrugia.github.io/resource-hints/preload-unused-resource
- https://kevinfarrugia.github.io/resource-hints/preload-incorrect-request-credentials


@bazzadp anything further needed to have the console output available for query, or is everything in the HAR already available?

**Comment by kevinfarrugia** [comment]
Looks like it's working well:

```
_consoleLog: [
{
source: "other",
level: "warning",
text: "A preload for 'https://kevinfarrugia.github.io/resource-hints/fonts/roboto-regular.woff2' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.",
timestamp: 1621951673550.989,
url: "https://kevinfarrugia.github.io/resource-hints/preload-incorrect-request-credentials"
}
]
```

**Comment by pmeenan** [comment]
I believe so.  It'll be interesting to see how much bigger the pages table queries get with the console logs included now.

**Comment by rviscomi** [comment]
@kevinfarrugia the [outline](https://docs.google.com/document/d/1zIKdkS65X9u3rGZOn1kG0rk9YveFb0zhdORBFOoIgQQ/edit?usp=sharing) is coming along very nicely! Thanks for keeping on that. Just a reminder that it should be completed by June 15, but it looks like you're in good shape to meet that milestone.

Could you also please update the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2158#issue-868436290) to check off Milestone 0 now that your content team is fully staffed with authors/reviewers/analysts? Keeping the chapter metadata up to date is helpful for us to monitor everyone's progress at a glance in #2179. Thanks!

**Comment by rviscomi** [comment]
Hey @kevinfarrugia, how are you feeling about the outline? Looking like a lot of great content in there now, but just not sure if you're still working on it. Please check off Milestone 1 [above](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2158#issue-868436290) when you're satisfied with it. Thanks!

**Comment by kevinfarrugia** [comment]
Thank you @rviscomi . I will be going through the queries together with @Nithanaroy and if we're happy with them I will check off Milestone 1.

**Comment by Zizzamia** [comment]
Hey @kevinfarrugia let me know if you need any help from connecting the data from last year to this year. Or you need any insights on the how we wrote the [doc from last year](https://docs.google.com/document/d/1qsJWq7eKdif2egt54G3jmZzK4PkyoIX8g4o4UzlJGEw/edit?usp=sharing).

**Comment by kevinfarrugia** [comment]
@pmeenan I can confirm that the _consoleLog is available in the `payload` column in the `pages` table (and also `sample_data` since this was updated to the June crawl). 🎊

**Comment by rviscomi** [comment]
👋 Hi @kevinfarrugia @Nithanaroy, just checking in on the chapter progress. How is the analysis coming along?

**Comment by kevinfarrugia** [comment]
We are communicating on Slack and will be splitting up the effort. Hopefully we will have some good progress soon.

**Comment by rviscomi** [comment]
@kevinfarrugia @siakaramalegos @Zizzamia @samarpanda @Nithanaroy

**Thank you** all for your hard work getting this chapter over the finish line in time for the pre-release! Congratulations on finishing the chapter, and I'm excited to see us launch the rest of the chapters along side it on Wednesday 🎉

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏
