### ISSUE TITLE
Structured Data 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2174]
# Part I Chapter 4: Structured Data

If you're interested in contributing to the Structured Data chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @jonoalderson | @jonoalderson @cyberandy | @kevinmarks @vdwijngaert @jvandriel @philbarker | @GregBrimble  | @jvandriel @JasmineDWillson | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Structured Data resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/19KDSv4olAXUHUV6hq4X4Cb-lNziqvVesgXXxVktrw4c/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/structured-data
[~google-sheets]: https://docs.google.com/spreadsheets/d/1uEA217YjpX1xdRVBnIz9ekjpjIrpGIh5GwUxvnzJNig/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/structured-data.md

**Comment by jono-alderson** [comment]
As discussed in Slack, I'd be very keen to author this. I'd also be happy to take my hat out of the 'Author' ring for #2148 so as to be able to resource this effectively (which I've updated accordingly).

**Comment by rviscomi** [comment]
@jono-alderson thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) by finding contributors to be a peer reviewer and analyst
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2174#issue-869195089
[~google-doc]: https://docs.google.com/document/d/19KDSv4olAXUHUV6hq4X4Cb-lNziqvVesgXXxVktrw4c/edit?usp=sharing

**Comment by GregBrimble** [comment]
Hey @jono-alderson ,

If you'll have me, I'd love to help out with the analysis for this chapter, this year!

**Comment by jono-alderson** [comment]
> Hey @jono-alderson ,
> 
> If you'll have me, I'd love to help out with the analysis for this chapter, this year!
That'd be wonderful, thanks! NB, I'm aiming to start outlining a plan and firing out some comms this weekend :)

**Comment by rviscomi** [comment]
Hi @jono-alderson just checking in. Here are some tips to help keep the chapter on track:

- Request edit access to the [doc](https://docs.google.com/document/d/19KDSv4olAXUHUV6hq4X4Cb-lNziqvVesgXXxVktrw4c/edit?usp=sharing) and start brainstorming an outline for the chapter
- Consider announcing in to your professional networks that you're looking for co-contributors knowledgable in structured data to join the chapter
- Edit the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2174#issue-869195089) to keep the chapter metadata in sync with all reviewers and analysts and also any completed milestones (helpful for us to monitor staffing at a glance in https://github.com/HTTPArchive/almanac.httparchive.org/issues/2179)

⚠️ Note that if we're unable to meet Milestone 0 by May 31 we may have to close this chapter and refocus our efforts on other chapters.

**Comment by jono-alderson** [comment]
> Happy to help if you guys need any more reviewers :)

Thanks - more reviewers are definitely welcome! I have a feeling that we're going to need lots of hands on deck for this!

**Comment by jvandriel** [comment]
I'm happy to join and help out as well - also very curious to see the outcome

**Comment by rviscomi** [comment]
> @rviscomi I don't appear to be able to edit the top comment; do I need some permissions?

@jono-alderson you'll need to accept our invitation to join the HTTP Archive team in order to get edit access on GitHub. Check your email or visit https://github.com/HTTPArchive/ to accept.

**Comment by jono-alderson** [comment]
Oh no, the invitation expired!

**Comment by rviscomi** [comment]
Resent!

**Comment by JasmineDWillson** [comment]
Also happy to contribute as author, editor or both!

**Comment by jono-alderson** [comment]
Hi Jasmine, welcome on board!

FYI, I've created a Slack channel for us to coordinate in (https://httparchive.slack.com/archives/C021GGN9W4D), and, I'll start collating some initial thoughts on overarching structures, constraints, requirements etc, in the coming days.

**Comment by kevinmarks** [comment]
The slack wants me to have an httparchive email address to sign in - can you invite me directly at kevinmarks@gmail.com please

**Comment by GregBrimble** [comment]
Invited, @kevinmarks  :)

**Comment by cyberandy** [comment]
Same, can you invite me on slack using andrea@wordlift.io? Thanks

**Comment by GregBrimble** [comment]
Also invited, @cyberandy !

**Comment by rviscomi** [comment]
Here's the sharable link for anyone to join the Slack channel: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by jono-alderson** [comment]
Looks like we have everybody in Slack except for @vdwijngaert; are you able to join us, Koen? :)

**Comment by philbarker** [comment]
@jono-alderson I'm here because @jvandriel asked, then I saw your tweet asking for involvement from people with expertise in Dublin Core / other metadata.  I might be able to help as reviewer, if you still need such help.

**Comment by jono-alderson** [comment]
Hi @philbarker, thanks for reaching out! That'd be amazing; I'll add you to the team list! I know I'm personally weak on knowledge around DC, so keen to have an expert involved!

Please feel free to jump into the Slack channel, and contribute any ideas/direction, etc!

**Comment by rviscomi** [comment]
All, the outline in the [chapter doc](https://docs.google.com/document/d/19KDSv4olAXUHUV6hq4X4Cb-lNziqvVesgXXxVktrw4c/edit?usp=sharing) is looking great. Nice work! 🚀 

@jono-alderson is the outline complete, or are you still adding to it?

**Comment by jono-alderson** [comment]
Getting there! 
Hoping for a bit more feedback from the crew, as I feel there's more we could do without being too over-ambitious. Any ideas, folks?

**Comment by GregBrimble** [comment]
One thing I might suggest would be a deeper integration with knowledge graphs like Wikidata. If I've got this structured data on a page:

```json
{
  "@type": "Person",
  "name": "Greg Brimble",
  "nationality": {
    "@type": "Country",
    "name": "United Kingdom"
  },
  "sameAs": ["https://www.wikidata.org/wiki/Q52444075"]
}
```

and Wikidata has this:

```txt
"instance of" → "human"
(P31 → Q5)

"country of citizenship" → "United Kingdom"
(P27 → Q145)
```

- How much overlap is there? Does the structured data provide information not found in Wikidata, or vice-versa?
- Are there any inconsistent claims?
- Do the types of the entity match?
- etc.

This is getting dangerously close to what my undergraduate dissertation was on 😅 The difficulty is in doing the ontology matching (finding equivalent properties and entities), which might be a bit out-of-scope for this analysis (e.g. Schema.org's "Person" ≠ Q5, but Schema.org's "nationality" === P27).

**Comment by jono-alderson** [comment]
That'd be pretty awesome, but I think that comparing to external sources at scale is going to be waaayyy out of scope.
We should definitely put more attention on `sameAs` declarations, though; there's bound to be some interesting findings in directing common hostnames and patterns in there.

**Comment by JasmineDWillson** [comment]
Might be interesting to touch on the use of sameAs:
1.  In terms of its limitations
- e.g. [When owl:sameAs isn’t the Same: An Analysis of Identity Links on the Semantic Web](https://www.w3.org/2009/12/rdf-ws/papers/ws21) 
2. Or ways that others have tried to navigate mapping to terms that are not entirely equivalent
- e.g. the [CWRC ontology](https://sparql.cwrc.ca/testing/cwrc.html)'s "has functional relation" predicate which "Relates...to external terms that are semantically incommensurate but that may be pragmatically related for processing purposes such as search and retrieval"

without diving too deeply into the mire of ontology mapping...

**Comment by rviscomi** [comment]
Hey @jono-alderson, could you give an update on the chapter outline? I see some new topics added today, but not sure if it's still being worked on. If it's finalized you could check off Milestone 1 [above](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2174#issue-869195089), otherwise let us know when you think it'll be ready. Thanks!

@GregBrimble please take a close look at the outline to see whether we need any [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) to extract structured data info from the DOM at runtime. Those would need to be written and merged no later than the end of the month to be added to the test pipeline in time.

**Comment by GregBrimble** [comment]
And we've got the run's results! July's data is up so we can now play around in BigQuery.

I've started the queries in #2293, and have requested edit access to the [results sheet](https://docs.google.com/spreadsheets/d/1uEA217YjpX1xdRVBnIz9ekjpjIrpGIh5GwUxvnzJNig/edit) so I can start putting stuff down there. Checked the error log as a first priority, and so far, it looks pretty good. We have our structured data custom metrics on 13,775,158 of the 13,778,213 pages we've run against. We captured 508 error logs, and I'm assuming the rest (2,547) failed so hard that we couldn't even capture the exception. 99.98% success is good enough for me.

This analysis is due September 30, but I can't imagine it takes nearly that long. The hardest bit will be the JSON-LD parsing, which in all likelihood I'm going to do locally. I'll do bits and pieces over the next few days, so keep an eye on that linked PR to follow along :)

**Comment by rviscomi** [comment]
👋 Hi @jono-alderson @cyberandy @GregBrimble, just checking in on the chapter progress. How is the analysis coming along?

**Comment by GregBrimble** [comment]
Hey, made decent progress the weekend before last, but it's a busy week at work, this week, so haven't had a chance to get back to it. I'll get this completed next weekend ☺️

**Comment by jono-alderson** [comment]
Any updates from your side, @GregBrimble ?

**Comment by rviscomi** [comment]
@jonoalderson @cyberandy @kevinmarks @vdwijngaert @jvandriel @philbarker @GregBrimble @jvandriel @JasmineDWillson

Thank you all for your hard work getting this chapter over the finish line in time for the pre-release—Structured Data has been the most-read chapter in the past couple of weeks! Congratulations on finishing the chapter, and I'm excited to see us launch the rest of the chapters along side it on Wednesday 🎉 

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏
