### ISSUE TITLE
Copyedit completed contents

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#218]
Go through each chapter and "contentful" page to ensure that it fits our "work fun" voice, fix spelling and grammar, and finalize formatting. See the [Editors' Wiki](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Wiki) for an explicit list of best practices.

Whenever possible, also try to interlink chapters (#253).

- [x]	1. JavaScript	#131 @obto
- [x]	2. CSS	#132 @rachellcostello 
- [x]	3. Markup	#133 @rviscomi
- [ ]	4. Media	#170 @rachellcostello 
- [x]	5. Third Parties	#134 @bazzadp 
- [x]	6. Fonts	#143 @bazzadp
- [x]	7. Performance	#171 @rachellcostello 
- [x]	8. Security	#158 @bazzadp for first round + someone else
- [x]	9. Accessibility	#155 @obto
- [x]	10. SEO	#163 @rachellcostello 
- [x]	11. PWA	#164 @bazzadp 
- [x]	12. Mobile web	#147 @rviscomi 
- [x]	13. Ecommerce	#135 @bazzadp 
- [x]	14. CMS	#169
- [x]	15. Compression	#145 @bazzadp 
- [x]	16. Caching	#172 @bazzadp
- [x]	17. CDN	#149
- [x]	18. Page Weight	#144 @obto 
- [x]	19. Resource Hints	#136 @rviscomi 
- [x]	20. HTTP/2	#173 @rachellcostello 
- [x] Methodology #202 @bazzadp 
- [x] Home #212 @bazzadp 
- [x] Foreword #285 @bazzadp

**Comment by rviscomi** [comment]
@ekharvey @Meggin @rachellcostello IIRC you've all expressed interest in helping out with copyediting. If you still have time over the next 3 weeks to review content, it'd be a huge help! 🙏

**Comment by rviscomi** [comment]
The following chapters are merged and ready for editing:

3. Markup
5. Third Parties
10. SEO
11. PWA
20. HTTP/2

Markdown files are available at [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019).

Most of them still need data viz embedded but that shouldn't block.

**Comment by rachellcostello** [comment]
Of course, happy to help with proofreading and editing wherever needed! I can start off with the SEO chapter, but I can tackle some of the others as well so feel free to divide up the remaining chapters and assign me more.

**Comment by rviscomi** [comment]
Great thanks @rachellcostello! Yes, go ahead and start with the SEO chapter.

To make sure everyone is following the same guidelines I started a [wiki page](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Wiki) for us to drop in our editing decisions. As you go through the content and establish new editing rules, add them to the wiki.

**Comment by obto** [comment]
Currently reviewing and editing the caching, javascript, mobile web and a11y chapters. After those have been merged in, I'd be happy to edit the rest :+1:

**Comment by rviscomi** [comment]
@rachellcostello after #249 is merged the Performance chapter should be ready for editing. Just had to rewrite it a bit and add data viz.

**Comment by bazzadp** [comment]
@rviscomi, @rachellcostello, @obto what do you think of https://github.com/HTTPArchive/almanac.httparchive.org/issues/253 that I've just raised? One to bear in mind as we copyedit the remaining chapters?

P.S. And sorry if that sounds like a dig at your chapter @rachellcostello - it honestly isn't meant like that!

**Comment by rachellcostello** [comment]
Not at all @bazzadp - I completely agree! I believe that placeholders were left for internal links as we didn't know what the final URLs would be for the other chapters, so it was a good example for you to reference :)

**Comment by rachellcostello** [comment]
I was going to proofread some other chapters while waiting for [#249](https://github.com/HTTPArchive/almanac.httparchive.org/pull/249) to be merged, but looks like the list of finished chapters have other editors already assigned currently. I'll keep an eye out for any new chapters in [src/content/en](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019), but let me know if there's anything you need help with in the meantime @rviscomi and @obto

**Comment by rachellcostello** [comment]
Oh wait looks like HTTP/2 is ready, I'll take a look at that one too.

**Comment by bazzadp** [comment]
Be kind - that one’s mine! 😀 Ping me if you’ve any questions.

Can you do me a favour and correct my name in the meta data at the top from my twitter name (tunetheweb) to my GitHub name (Bazzadp) since that’s the convention we’re going for?

Also now we know the URL structure as per https://github.com/HTTPArchive/almanac.httparchive.org/issues/253 if you could correct the other chapter links I have to those that would be good.

**Comment by rviscomi** [comment]
@obto since you wrote the mweb chapter I'll edit it with a fresh set of eyes :)

**Comment by obto** [comment]
That'd be great, and sorry for the delay in copyediting. I'll be starting
tonight and tomorrow

**Comment by rviscomi** [comment]
The current list of chapters ready for editing are:

- Performance
- Accessibility
- Mobile Web
- Compression
- Caching
- Page Weight
- Resource Hints
- HTTP/2

A few more are wrapping up peer review and will be ready for editing soon.

I'm in the process of editing Mobile Web (#305). @rachellcostello have you started your review of HTTP/2 or Performance?

**Comment by bazzadp** [comment]
@obto I see you're down to Copy Edit the Caching Chapter. Want me to take that over since you were a reviewer on it? Fresh pair of eyes and all that. Plus I've already nitpicked @paulcalvano once for Compression so I'm sure he'd appreciate the same annoying guy giving him grief about his other chapter too! 😉

**Comment by obto** [comment]
@bazzadp That'd be great. I'll move straight to the JS chapter :)

**Comment by rviscomi** [comment]
@obto JS is not quite merged so maybe start on something else in case it changes.

**Comment by obto** [comment]
@rviscomi Oh that completely slipped my mind. I'll checkout page weight then

**Comment by rachellcostello** [comment]
> The current list of chapters ready for editing are:
> 
> * Performance
> * Accessibility
> * Mobile Web
> * Compression
> * Caching
> * Page Weight
> * Resource Hints
> * HTTP/2
> 
> A few more are wrapping up peer review and will be ready for editing soon.
> 
> I'm in the process of editing Mobile Web (#305). @rachellcostello have you started your review of HTTP/2 or Performance?

@rviscomi I'm working on HTTP/2 at the moment, should be finished today and I'll try and tackle Performance today too.

**Comment by rachellcostello** [comment]
Finished HTTP/2 and Performance, happy to take Page Weight and/or Resource Hints next.

**Comment by rviscomi** [comment]
Created an Editors team so we can bulk notify/assign now :)

cc @HTTPArchive/editors

**Comment by rviscomi** [comment]
JS and CSS are ready for editing.

**Comment by obto** [comment]
@rachellcostello Sorry i forgot to edit the list in here to show I've been working on page weight. Already halfway finished and a PR up.

**Comment by rviscomi** [comment]
Media is also ready for editing.

**Comment by bazzadp** [comment]
I've added some of the [steps I'm doing to the Editor's Wiki](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Wiki#suggested-process).

In part to remind myself, in part for future, and in part in case someone comes a long and offers to help this weekend!

Free free to add to it!

**Comment by rviscomi** [comment]
@rachellcostello have you had a chance to edit the Media chapter?

**Comment by bazzadp** [comment]
> @rachellcostello have you had a chance to edit the Media chapter?

Spoke to @rachellcostello and she's travelling so I said I'd take first pass at this, after I fix the typos in https://github.com/HTTPArchive/almanac.httparchive.org/issues/460.
