### ISSUE TITLE
Audit the website for performance issues

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#413]
Related: #286 and #303. Make sure we're not doing anything silly to hurt performance.

I'm aware that embedding 25 Sheets iframes is probably not a great idea for performance. We can look into preconnecting to the origin and lazy loading the iframes.

The audit should ideally happen before launch just so we know if we're doing anything egregious. Any P0 performance issues should be fixed prior to launch (within 24 hours). Everything else can be resolved after launch (apres ski).

cc performance experts @andydavies @paulcalvano 

---

### Performance issues

- [x] **P1** home page header background image https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552175467
- [x] **P1** load appropriate data viz https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552176411
- [x] **P2** lazy load footer and mobile images https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552175796
- [ ] **P2** set a long TTL for static images https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552176079
- [x] **P2** lazy load data viz iframes/images and author avatars https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552176643

**Comment by bazzadp** [comment]
> I'm aware that embedding 25 Sheets iframes is probably not a great idea for performance. We can look into preconnecting to the origin and lazy loading the iframes.

Just noting that lazy loading images (and possibly iframes) is being discussed in https://github.com/HTTPArchive/almanac.httparchive.org/issues/351

**Comment by rviscomi** [comment]
Yes I definitely think #351 would be helpful.

This issue can tell us how significant the perf impact of not lazy loading is.

**Comment by bazzadp** [comment]
Any ideas why Lato font loads so many times?:

![image](https://user-images.githubusercontent.com/10931297/68541381-89cb4800-0396-11ea-884a-fa9087173bc8.png)

**Comment by rviscomi** [comment]
In base.html we load the fonts here: `<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i, 900|Poppins:300,400,700,900&display=swap" rel="stylesheet">`.

I think it's loading one font file for each weight/style combo.

**Comment by rviscomi** [comment]
The home page background image is very large and provides contrast to the white text at the top of the page. Because it's so large, it takes a few seconds to load for the first time, so the text is invisible, except for the yellow buttons:

![image](https://user-images.githubusercontent.com/1120896/68541431-37693780-0354-11ea-8800-5dd4a7098bb0.png)

We should use a CSS-based background color as a placeholder until the image loads, and/or look into optimizing that background image so it doesn't load as slowly.

**Comment by rviscomi** [comment]
Images used in the footer and mobile design are loading immediately. Below-fold images should be lazy loaded and mobile-specific images should never load for desktop.

![image](https://user-images.githubusercontent.com/1120896/68541474-e73ea500-0354-11ea-89f8-4a0f79879312.png)

**Comment by rviscomi** [comment]
Extend the cache lifetime for static images
![image](https://user-images.githubusercontent.com/1120896/68541548-a1cea780-0355-11ea-9a10-cbc44ae9973d.png)

https://www.webpagetest.org/performance_optimization.php?test=191110_MK_600ab0b42469c8fb2a03fdbf34132dd6&run=1#cache_static_content

**Comment by rviscomi** [comment]
Mobile-specific data viz is still loaded on desktop chapter pages. I would have thought the `display: none` style prevented this.

![image](https://user-images.githubusercontent.com/1120896/68541596-46e98000-0356-11ea-9738-face08b1924b.png)
https://www.webpagetest.org/result/191110_J7_f4bc44580c3abfae6451fa9b72659012/1/details/#waterfall_view_step1

**Comment by rviscomi** [comment]
Embedded data viz iframes should be lazy loaded until in view (#351).

Author avatars should also be lazy loaded.
 
![image](https://user-images.githubusercontent.com/1120896/68541636-c11a0480-0356-11ea-9ca8-487507d17baf.png)

https://www.webpagetest.org/result/191110_J7_f4bc44580c3abfae6451fa9b72659012/1/details/#waterfall_view_step1

**Comment by AymenLoukil** [comment]
> Extend the cache lifetime for static images
> ![image](https://user-images.githubusercontent.com/1120896/68541548-a1cea780-0355-11ea-9a10-cbc44ae9973d.png)
> 
> https://www.webpagetest.org/performance_optimization.php?test=191110_MK_600ab0b42469c8fb2a03fdbf34132dd6&run=1#cache_static_content
Already detected in #286

**Comment by AymenLoukil** [comment]
Also i would add that many resources paths are relative and not absolute. This could make additional time to check protocol / redirect etc.

**Comment by bazzadp** [comment]
> Also i would add that many resources paths are relative and not absolute. This could make additional time to check protocol / redirect etc.

Nah, don't think that's the case! Relative paths are gooood.

**Comment by AymenLoukil** [comment]
> > Also i would add that many resources paths are relative and not absolute. This could make additional time to check protocol / redirect etc.
> 
> Nah, don't think that's the case! Relative paths are gooood.

You serious ? ^^

**Comment by rviscomi** [comment]
I'm not aware of any reason not to use relative paths. It doesn't incur any overhead AFAIK. Browsers can quickly canonicalize the URL on the fly.

Maybe you're thinking of navigating to a page, for example `example.com` which redirects to `https://example.com` which redirects to `https://example.com/`?

**Comment by bazzadp** [comment]
> You serious ? ^^

Yes. What's the concern here?

You mean it says things like:

`<img src="/static/...`

As opposed to"

`<img src="https://almanac.httparchive.org/static/...`

??

**Comment by AymenLoukil** [comment]
> I'm not aware of any reason not to use relative paths. It doesn't incur any overhead AFAIK. Browsers can quickly canonicalize the URL on the fly.
> 
> Maybe you're thinking of navigating to a page, for example `example.com` which redirects to `https://example.com` which redirects to `https://example.com/`?

This is ok but i'm talking about resources paths. I believe that since we should be on HTTPS, it would be better to precise the absolute path. 
Webhint does check for it : https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/
Google Lighthouse team are thinking to implement this audit too.
There is also a security concern but mainly for HTTP websites / apps. @bazzadp 

In our case, i don't think it has a visible impact, just a best practice.

**Comment by bazzadp** [comment]
> https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/

That means don't do this:

`<script src="//www.google-analytics.com/analytics.js" async></script>`

As that loads http://www.google-analytics.com/analytics.js when on HTTP version of your site and https://www.google-analytics.com/analytics.js when on HTTPS and better to load same over both as will be referenced in cache for both so saves a double download. Plus better for security (if an assets is available over HTTPS then why not load it over HTTPS!).

It has nothing to do with relative references to links on your own site like the examples I gave in https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552178172

**Comment by bazzadp** [comment]
> It has nothing to do with relative references to links on your own site like the examples I gave in [#413 (comment)](https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552178172)

Well technically I suppose it it could be same thing if we had mixed site (i.e. some pages on HTTP and some on HTTPS) as, for example, specifying our logo always being loaded over HTTPS even on HTTP would prevent a double download. But since we don't have a mixed site, this is a non-issue.

Relative paths allow for cleaner, less-verbose code and launching dev envs while loading assets locally.

**Comment by AymenLoukil** [comment]
> > https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/
> 
> That means don't do this:
> 
> `<script src="//www.google-analytics.com/analytics.js" async></script>`
> 
> As that loads http://www.google-analytics.com/analytics.js when on HTTP version of your site and https://www.google-analytics.com/analytics.js when on HTTPS and better to load same over both as will be referenced in cache for both so saves a double download. Plus better for security (if an assets is available over HTTPS then why not load it over HTTPS!).
> 
> It has nothing to do with relative references to links on your own site like the examples I gave in [#413 (comment)](https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552178172)

Ok thank you @bazzadp :)

**Comment by bazzadp** [comment]
Oh and btw the title of that page is "No Protocol-Relative URLs" not "No Relative URLs"

**Comment by paulcalvano** [comment]
Just opened an issue about the static content TTL and then realized it's already being tracked here - https://github.com/HTTPArchive/almanac.httparchive.org/issues/423.

**Comment by catalinred** [comment]
> The home page background image is very large and provides contrast to the white text at the top of the page. Because it's so large, it takes a few seconds to load for the first time, so the text is invisible, except for the yellow buttons:
> 
> ![image](https://user-images.githubusercontent.com/1120896/68541431-37693780-0354-11ea-8800-5dd4a7098bb0.png)
> 
> https://www.webpagetest.org/video/compare.php?tests=191110_J7_f4bc44580c3abfae6451fa9b72659012,191110_MK_600ab0b42469c8fb2a03fdbf34132dd6,191110_HG_49bdb23fcbc8952c67d75e0c08a6b198,191110_8T_02272f25cf4fcf6bc73f58e1ea8f2e1e,191110_M6_ec2abd0fd85a56c09523e42337d706e0
> 
> We should use a CSS-based background color as a placeholder until the image loads, and/or look into optimizing that background image so it doesn't load as slowly.

This something I'd be interested to work on. Is there a separate issue for this?

**Comment by rviscomi** [comment]
SVG sounds like a good idea. @mikegeyser was also looking into improving the performance of this image. Did you make any progress, Mike?

**Comment by catalinred** [comment]
> SVG sounds like a good idea. @mikegeyser was also looking into improving the performance of this image. Did you make any progress, Mike?

In case @mikegeyser needs some help here, I'd recommend turning the `intro-background-fit.png` image into a .svg and then encode it to base64 to avoid the above webpagetest scenario when having white text on white background until the `intro-background-fit.png` request is fulfilled.

`intro-background-fit.png` is suitable to convert to a .svg file by not having lots of detail. We'd have a background image from the start so no white text on a white (blank) background and we'd have minus one HTTP request in the background.

What do you think?

**Comment by mikegeyser** [comment]
I'll definitely take a look at doing that @catalinred. The alternative that I was playing around with on Sunday was using a solid background and [lazy loading the image and swapping it](https://css-tricks.com/the-complete-guide-to-lazy-loading-images/#article-header-id-4). It does mean including some javascript to do the switch, however, which I'm not sure about.

Seems like it's all tradeoffs...

**Comment by mikegeyser** [comment]
@catalinred @rviscomi I pushed what I was working on as a part of #485. I'm really not tied to that way of doing it, and would like feedback.

We can embed the image as a data uri directly, and that's simpler, but it does seem as there is a [non-trivial tradeoff ](https://css-tricks.com/data-uris/#article-header-id-4) in making the CSS file larger with image data (although that link is super old). This was is at least still cacheable?

Anyway, let me know what you think. :)

**Comment by rviscomi** [comment]
@bazzadp tackled the lazy loading issues in #484 (ticking those checkboxes as resolved)

**Comment by bazzadp** [comment]
@bazzadp found the reasons, but not the answer. Could do with some help there.

Also late here in Ireland so going to be giving up for the night soon if anyone wants to take it over?

**Comment by rviscomi** [comment]
No worries. The fix was just deployed live so it's worth rerunning another performance test to validate it.

**Comment by AymenLoukil** [comment]
I run Lighthouse, Lazy loading seems to work fine now.

This image is big (400 KB ! ) to resize + compress.
https://almanac.httparchive.org/static/images/methodology-banner.png 


Why not self host contributors avatars  ? Erik Nygren's one > 160 KB.

Figures images could be lighter on size.

**Comment by bazzadp** [comment]
> I run Lighthouse, Lazy loading seems to work fine now.

👌

> This image is big (400 KB ! ) to resize + compress.
> https://almanac.httparchive.org/static/images/methodology-banner.png

I thought it did that automatically?

> Why not self host contributors avatars ? 

I'm not sure I agree. I think it's nice for people to be able to alter their avatars on GitHub rather than have to do a PR.

> Erik Nygren's one > 160 KB. Figures images could be lighter on size.

We load the 200px version. Now on author pages we only load a 60 x 60 pixel one so that's arguably a bit big. But only one image, that's now lazy-loaded, so not a big deal.

However on contributors page we load 100 x 100 and with retina screens, 200 x 200 is probably better. Again they are lazy-loaded so not too concerned.

**Comment by AymenLoukil** [comment]
> We load the 200px version. Now on author pages we only load a 60 x 60 pixel one so that's arguably a bit big. But only one image, that's now lazy-loaded, so not a big deal. 
Not always :) since it is shuffling on reload

**Comment by bazzadp** [comment]
> > We load the 200px version. Now on author pages we only load a 60 x 60 pixel one so that's arguably a bit big. But only one image, that's now lazy-loaded, so not a big deal.
> 
> Not always :) since it is shuffling on reload

Contributor is shuffling on reload - not chapters. See my second comment for contributors page 😀

**Comment by AymenLoukil** [comment]
> Contributor is shuffling on reload - not chapters. See my second comment for contributors page

Yeah i mean, when Erik Nygren's is displayed on the "Above the fold zone", it won't be lazy loaded.
