### ISSUE TITLE
A couple of small Japanese translations required

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#850]
Before I forget:

- [x] In #837 we added a a `fig2-description`. I auto translated it to Japanese but probably not that great.
- [x] In #833 we added to the Accessibility statement to explain how we made an accessible PDF.
- [x] Translate Japanese in #857 

Can we update the Japanese versions with these changes?

**Comment by ksakae1216** [comment]
@bazzadp , OK, I will translate.
Please wait.

**Comment by bazzadp** [comment]
Got one more for you, if you don't mind.

Would this:
```
{% macro show_description(id) %}図{{ id }}の説明を表示{% endmacro %}
{% macro hide_description(id) %}図{{ id }}の説明を非表示{% endmacro %}
```
be an accurate translation of this?:
```
{% macro show_description(id) %}Show description of Figure {{ id }}{% endmacro %}
{% macro hide_description(id) %}Hide description of Figure {{ id }}{% endmacro %}
```

This is part of #857 and will show as button text below images, like this:

![image](https://user-images.githubusercontent.com/10931297/82723168-b573a700-9cc4-11ea-9856-8d5c8f36e353.png)

Here's the English version:

![image](https://user-images.githubusercontent.com/10931297/82723152-9bd25f80-9cc4-11ea-9b7d-4f8d37db14db.png)

If that's not accurate translation could you review #857 and suggest better text?

**Comment by ksakae1216** [comment]
@bazzadp , This translate is no problem.

**Comment by bazzadp** [comment]
Excellent - cheers for that!
