### ISSUE TITLE
JavaScript 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#897]
# Part I Chapter 2: JavaScript

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @tkadlec | @ibnesayeed @jadjoubran @ahmadawais @denar90  | @rviscomi @paulcalvano  | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @tkadlec

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1DYx3_QbwGgyauBotbQRYU-4fmkaQFO7XcLTb7q4BqHQ/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/02_JavaScript
[~results-sheet]: https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=2077755325

**Comment by housseindjirdeh** [comment]
I can definitely help review this chapter!

Some amazing people in community that I'd like to nominate (only if they're interested in writing for the 2020 Web Almanac of course):

* @tkadlec
* @benschwarz
* @thefoxis
* @denar90
* @ahmadawais 
* @jadjoubran

**Comment by ibnesayeed** [comment]
I should be able to review this chapter.

**Comment by ahmadawais** [comment]
@housseindjirdeh thanks for the mention. I've already asked to be the author of this JavaScript chapter for 2020 Almanac. I'd love more contributors. And your content from 2019 is going to be quite helpful as it laid the foundation. We might also include a heading on JAMstack this year. 😇🙌

**Comment by rviscomi** [comment]
@tkadlec thank you for agreeing to be the lead author for the JavaScript chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. Several other people were interested or nominated (see below), so that's a great place to start. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1DYx3_QbwGgyauBotbQRYU-4fmkaQFO7XcLTb7q4BqHQ/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/javascript) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

To everyone else who has been nominated:

@ahmadawais
@hemanth
@jadjoubran
@benschwarz
@thefoxis
@denar90

we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by rviscomi** [comment]
Thanks @ibnesayeed I'll put you down as a reviewer!

**Comment by thefoxis** [comment]
thank you for the shout @housseindjirdeh! I don't think I'm the best fit for JS, plus I will be contributing to the performance chapter so I'll pass on this one 😸

**Comment by ahmadawais** [comment]
Thank you, @rviscomi. Looking forward to contributing as an author and reviewer @tkadlec.

**Comment by jadjoubran** [comment]
Thank you @rviscomi, I'm still interested in peer reviewing 👍

**Comment by tkadlec** [comment]
Pretty excited about this (thanks for the mention @housseindjirdeh).

Looks like we've already got a solid crew of reviewers forming. Anyone keen to help with the analyst side of things?

I'm re-reading last year's chapter and will start dropping some ideas in the Google Doc for areas I think could be interesting to add this year.

**Comment by tkadlec** [comment]
@thefoxis We'll probably need to coordinate with you to some extent. :) I think a section here on how JS decisions impact the core trio of accessibility, security and perf would be quite interesting and could be fleshed out quite a bit more this year. I see from a comment on your performance chapter you're also thinking along those lines (great minds and all that). So I'll just want to make sure whatever we end up on here doesn't step on your toes and compliments what you end up doing.

**Comment by thefoxis** [comment]
@tkadlec good point! let's keep an 👀 on both chapters and coordinate to not overlap too much. I think echoing the same sentiments is important and totally fine (such as the prevalence of js + its impact on ux/security/a11y/perf) but we should probably avoid an in-depth analysis of the same data 👍

**Comment by rviscomi** [comment]
@developit would you have any interest in helping to plan/review this chapter, or is there anyone else you think might be interested?

**Comment by obto** [comment]
Hey @tkadlec, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Anything you need from me to keep things moving forward?

**Comment by jaisanth** [comment]
I'm interested in being a reviewer, not sure if this is already filled up :-)

**Comment by denar90** [comment]
@housseindjirdeh thanks 🙌 
@rviscomi @obto @tkadlec if you still need some help I'd be happy to help 😃

**Comment by bazzadp** [comment]
@stoyan do you have any interest with helping out in this (or any other) chapter?

**Comment by tkadlec** [comment]
@jaisanth & @denar90 I'm always happy for more eyes on it. :) We also have zero analysts so far, if either of you would be game for that!

@jadjoubran @ahmadawais @ibnesayeed I dropped some ideas and a skeleton outline in the doc. I'd love to get your feedback! So far, I didn't stop much to consider _if_ anything can be measured—I figured we'd deal with that as we dig through the metrics and stuff.

In particular, I'd love to hear any angles you all think are being overlooked and, specifically, anything we can do to make the "which new api's are we using" bit a bit more fleshed out. It's probably the least interesting angle to me personally, so it's also the one that feels weakest.

@obto Feeling pretty good so far, other than our lack of analysts. :)

**Comment by ibnesayeed** [comment]
@tkadlec the outline looks good to me. I have added a couple of quick comments in the doc.

**Comment by obto** [comment]
@tkadlec Haha, yeah it looks like we'll have to share analysts between chapters like last year. If we don't find one for this chapter I'm happy to be the analyst until we do :). We'll keep you posted.

**Comment by jaisanth** [comment]
@tkadlec I'd be happy to review it :-)

**Comment by obto** [comment]
@jaisanth Our own @bazzadp just made a great post on how to get started as an analyst that I think you'd find to be super helpful https://github.com/HTTPArchive/almanac.httparchive.org/issues/914#issuecomment-659205330. 

After you check it out, let me know if you'd like to take on the analyst role for the chapter and I'll put your name down :heart:

**Comment by developit** [comment]
@rviscomi I can help in some capacity, not sure to what extent yet. I'll take a look at what's been done and refamiliarize myself with last year's JS section.

**Comment by jaisanth** [comment]
@obto Went through the Analysts' Guide. I'll sign up as an analyst then! Thanks for the great guide @bazzadp ! 👍

**Comment by obto** [comment]
@jaisanth awesome, i've put you down as the analyst. And now the full team has been assembled for the chapter :heart:

**Comment by rviscomi** [comment]
@jaisanth could you go to https://github.com/HTTPArchive to accept your invitation to the Analysts team? Also please request edit access to the [doc](https://docs.google.com/document/d/1DYx3_QbwGgyauBotbQRYU-4fmkaQFO7XcLTb7q4BqHQ/edit?usp=sharing) so you can work on metrics triaging. And if you'd like to chat with or get help from other analysts you can join us in the [`#web-almanac-analysts`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) Slack channel.

@developit let us know if you'll be able to contribute!

@denar90 let us know if you're interested in contributing as a [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide) and/or [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide). Both roles are especially needed for this chapter, which has a very broad scope.

(@tkadlec sorry to take command, just want to make sure the chapter stays on schedule. Feel free to drive it as you see fit.)

**Comment by denar90** [comment]
@rviscomi @tkadlec will be happy to review :)

**Comment by tkadlec** [comment]
@rviscomi No worries! I appreciate the help! 

@denar90 Sounds awesome, thanks!

**Comment by max-ostapenko** [comment]
@jaisanth Check out queries for Third-party chapter here: #1092 .
Some part of metrics can be reused among us I believe.
Feel free to reach out.

**Comment by rviscomi** [comment]
@jaisanth @tkadlec for the two milestones overdue on July 27 could you check the boxes if:

- the [outline](https://docs.google.com/document/d/1DYx3_QbwGgyauBotbQRYU-4fmkaQFO7XcLTb7q4BqHQ/edit?usp=sharing) has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) have been created and you've created a [draft PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track which feasible metrics have had their [queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/02_JavaScript) implemented

Keeping the milestone checklist up to date helps us to see [at a glance](https://github.com/HTTPArchive/almanac.httparchive.org/issues/989) how all of the chapters are progressing. Thanks for helping us to stay on schedule!

**Comment by jaisanth** [comment]
Hey @max-ostapenko and @rviscomi , Will spend time on this in the weekend.

**Comment by tkadlec** [comment]
@jaisanth I've started on documenting the metrics I think we'll need (and I think are feasible) in the document. Would you be able to have a look as well and help me flesh it out?

**Comment by tkadlec** [comment]
@rviscomi Is the deprecated API's audit running? Wondering if there's anything interesting to clean by reporting on deprecated API's in use?

**Comment by rviscomi** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit?usp=sharing

**Comment by rviscomi** [comment]
> @rviscomi Is the deprecated API's audit running? Wondering if there's anything interesting to clean by reporting on deprecated API's in use?

@tkadlec yes, the [deprecations audit](https://web.dev/deprecations/) is under `$.audits.deprecations` in the LHR.

**Comment by rviscomi** [comment]
@jaisanth what's the status of the analysis for this chapter?

**Comment by rviscomi** [comment]
@HTTPArchive/analysts this chapter is behind and could use some help on the analysis front. If anyone has the time, please comment here. I've signed myself up as a stopgap but I'd be happy to collaborate if anyone wants to join.

**Comment by obto** [comment]
@tkadlec in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by rviscomi** [comment]
@tkadlec we've completed the analysis in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1352 and the results are ready for your review in [this sheet](https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=2077755325). I've checked off the analysis milestone from the top of the issue. Let @paulcalvano and me know if you have any questions by @'ing us in the sheet.

**Comment by tkadlec** [comment]
@rviscomi @paulcalvano Thanks so much you two!!

Super excited to dig in. 👍

**Comment by tkadlec** [comment]
Starting to write and tease content. This is a really interesting point from Alex: https://twitter.com/slightlylate/status/1329801884949876736

Are we able to query framework usage by site popularity? I like Ilya's Head/Torso/Tail thing from this talk at performance.now() (see https://www.youtube.com/watch?v=vtIfVPtN6io&t=8m39s).

So I'm thinking, framework usage for Top 100, Top 10000 in addition to what we already have? What do you think @rviscomi  and @paulcalvano?

**Comment by tkadlec** [comment]
Also, is there any value _at all_ in showing how much more JS bytes we're using today versus a longer time span than just last year? Like this?

![Median JS Bytes by year (Desktop)](https://user-images.githubusercontent.com/66536/99819033-8ecbe700-2b14-11eb-8609-51a9f314e46d.png)

I think it's interesting because it shows that we're not talking about a one-year trend here—we add more constantly. But at the same time, I know there have been plenty of changes in HTTP Archive that may make this kind of comparison unreliable.

**Comment by rviscomi** [comment]
> Are we able to query framework usage by site popularity?

Not currently. Other chapters have also been interested in a popularity dimension but we don't yet have a good ranking dataset that has good coverage of the HTTP Archive dataset, so I've been advising them not to rely on site popularity at all.

> Also, is there any value at all in showing how much more JS bytes we're using today versus a longer time span than just last year? Like this?

If you have a story to tell about that data, I'd be supportive of using it. You're right that there have been a few changes to the dataset, but I think the median helps to smooth that out. The growth is undeniable. It would require additional queries. Would you be interested in running them and filing a PR to merge them with the [sql/2020/02_JavaScript](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/02_JavaScript) queries? The results would also need to be saved to the [public spreadsheet](https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=2077755325) to be visualized and embedded in the chapter. Let me know how much of that you'd be comfortable doing. @paulcalvano can help out as needed.
