### ISSUE TITLE
Media 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#900]
# Part I Chapter 5: Media

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @tpiros @bseymour | @nhoizey @colinbendell @dougsillars | @smatei | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @tpiros

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1ip2At9j6ba17odQwBbXDVU7qiLnHRnX8DflAfdQNb9c/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/05_Media
[~results-sheet]: https://docs.google.com/spreadsheets/d/1SZGpCsTT0u1MFBrxed7HA9FLAloL1dS8ZIng986LvS8/edit#gid=2077755325

**Comment by zcorpan** [comment]
See https://discuss.httparchive.org/t/how-many-pages-use-picture-with-source-media/1975 - data on how common "art direction" use case is would be nice. A simple proxy is pages that use `<picture><source media>`.

**Comment by nhoizey** [comment]
Hi, I'm not sure I can work on the technical implementation of queries/reports, but I can work on content as author or reviewer.

I already [suggested @eeeps](https://github.com/HTTPArchive/almanac.httparchive.org/issues/876#issuecomment-644738783) for this topic, but I could work with him, at least.

**Comment by rviscomi** [comment]
@tpiros thank you for agreeing to be the lead author for the Media chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1MlgtHSTXbog-zdBMZ-xswytCzgnujMDEvlFeNEuPblo/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/media) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

@eeeps @nhoizey @zcorpan we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by nhoizey** [comment]
I'm still interested 👍

**Comment by rviscomi** [comment]
Great, thanks @nhoizey! I've added you to the reviewers list.

**Comment by nhoizey** [comment]
Thanks Rick

**Comment by zcorpan** [comment]
I can contribute with ideas for things to query, and review.

**Comment by rviscomi** [comment]
Thanks @zcorpan! To clarify are you open to contributing as a [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [data analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), or both?

**Comment by zcorpan** [comment]
Reviewer + content planning part of data analyst.

**Comment by rviscomi** [comment]
Ok thanks! I'll leave the analyst role open in that case. I've put you down as a reviewer.

**Comment by tpiros** [comment]
I will try to get @eeeps to be a co-author or a reviewer (he is my colleague). I know he was nominated to be an author for another chapter, I'm not sure if he can take on yet another task tho :)

**Comment by rviscomi** [comment]
Thanks @tpiros, both sound like good options (coauthor or reviewer). You have the helm for this chapter so feel free to staff the team how you see fit.

@eeeps what other chapter were you nominated for/interested in? I only seem to have you down for this one.

**Comment by tpiros** [comment]
I'd like to have @dougsillars as a co-author! I am looking for reviewers and will send updates.

**Comment by rviscomi** [comment]
@tpiros Doug is a great choice for coauthor, but I'd like to try to steer you away from having the same person write a chapter multiple years in a row. One of the goals this year is to broaden the diversity of perspectives, so it'd be great to hear from someone new, especially someone from an underrepresented group in tech. 

@dougsillars @colinbendell  we'd still love to have you both contribute as a reviewers and/or analysts!

**Comment by LeaVerou** [comment]
I would nominate @svgeesus @chriscoyier @AmeliaBR for SVG!

**Comment by borisschapira** [comment]
Would love to hear from @SaraSoueidan in a chapter dedicated to SVG and SVG animation

**Comment by svgeesus** [comment]
I would love to see data on how many images have embedded color profiles (broken down by image format, by size, and perhaps by image usage (images in HTML, background images in CSS, and so on). Firefox recently enabled, and then swiftly retracted, a change that enabled color management for untagged images (assumed to be sRGB) and it was reported that chrome handles explicitly-tagged sRGB images and assumed-sRGB images by different code paths, so this sort of data would be timely.

Percentage of display-p3 (vs similar wide gamut spaces like AdobeRGB or ProPhoto) would be especially interesting right now.

**Comment by rviscomi** [comment]
We need to evaluate how much metadata we have on images. Since we don't have the capacity to store image binaries, that limits the types of metrics we're able to analyze. Worth investigating if there's anything we can do upstream in WebPageTest (with custom metrics or built-in logic).

**Comment by colinbendell** [comment]
Media context analysis is one of the biggest gaps in this part of the
chapter. This includes:
* Image format
* physical image dimensions
* metadata analysis (icc, xmp, etc)
* density correctness
* dominant colours, colour volume used (incl. bit depth)
* video bytes loaded,
* dash/cmaf use, along with resolution, bitrate selection

Also, we should really look at a better update for the "estimates" since
the progressive jpeg estimate is flawed (assumes 80% regardless if the jpeg
is already progressive but encoded with a higher pixel bit rate) as is the
webp calculation (doesn't account for context of applicability or
consistent perceptual quality).

**Comment by colinbendell** [comment]
I'd also love to nominate @eeeps and/or @jonsneyers as an author for this chapter

**Comment by colinbendell** [comment]
(also happy to review if more hands are needed)

**Comment by obto** [comment]
@colinbendell Put you down as a reviewer :)

**Comment by obto** [comment]
Hey @tpiros, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Anything you need from me to keep things moving forward?

**Comment by rviscomi** [comment]
Spoke with @tpiros. I can temporarily fill in as the analyst for this chapter as needed. But if anyone else is interested in taking that role, I'd be happy to give up the spot, or help walk them through the process. @HTTPArchive/analysts any takers for this or any other [`help wanted: analysts`](https://github.com/HTTPArchive/almanac.httparchive.org/labels/help%20wanted%3A%20analysts) issues?

**Comment by tpiros** [comment]
Hi @obto - I am close to having selected a co-author and will introduce him soon. I do have 2 reviewers (@colinbendell & @dougsillars) with a third one pending (@eeeps). As Rick was saying I am still looking for an analyst for the project.

**Comment by smatei** [comment]
Hello @tpiros and @rviscomi 
I would like to be the analyst. I was accepted as analyst for the [compression](https://github.com/HTTPArchive/almanac.httparchive.org/issues/916) chapter. As I am new into this, I started by checking out the analyst guide, looking over the 2019 article and queries, and try them in the big query console, for both 2019 and 2020 data sets. I want to figure out the httparchive table structure, sql format and metrics meaning. I will do the same for the media chapter if accepted.

Also, about the "whitelist so that any costs incurred to query the dataset are covered by HTTP Archive". I read in the guide that @rviscomi would give me coupon code.

**Comment by obto** [comment]
@smatei happy to have you onboard! And yes, we'll be providing all analysts a coupon to cover the costs of running the queries along with sample tables (much smaller and less expensive) you can test queries on

**Comment by svgeesus** [comment]
> dominant colours, colour volume used

That would be super interesting, the actual gamut volume used (rather than the full theoretical gamut).

**Comment by tpiros** [comment]
@smatei Welcome - glad to have you aboard! @rviscomi @obto - what is the process of obtaining the coupons since I'd also like to run a few queries myself.

**Comment by tpiros** [comment]
hi @rviscomi & @obto - I'd like to have @bseymour as a co-author for this chapter. I have already talk to him and he's on board :) I hope you'll accept him

**Comment by obto** [comment]
@tpiros Absolutely!

**Comment by obto** [comment]
@smatei Our own @bazzadp made a great post of how to get started with BQ analysis that I think you'd find super helpful https://github.com/HTTPArchive/almanac.httparchive.org/issues/914#issuecomment-659205330

Also don't forget to join the [`#web-almanac`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) slack if you haven't already so @paulcalvano can invite you to the Analysts channel and help set you up.

**Comment by smatei** [comment]
I have read the 2019 media article. Now I will move forward to reading and understanding the sql behind it. 

As a side note, some time ago when scraping and parsing pages for the [The Average Web Page](https://www.advancedwebranking.com/html/) study, I found some pages that were extremely large - HTML code. Why, because the images were base 64 embedded in the HTML code. The uncompressed size of the page was 30MB or even 50MB. Most of these pages were scoring low in Lighthouse.  Here are some examples:

snoqualmievalleyeldercare.com

surprizeshop.co.uk

trails.dcnr.pa.gov

hartlepooltraining.co.uk

Is there any interesting correlation that could be done here? Embedded/not embedded, HTML size, performance score? Or is the performance driven mostly by other aspects and not by the embedded images. I understand that the purpose of embedding them is to transfer only one file instead of multiple files.

**Comment by obto** [comment]
@tpiros Lot of awesome discussion going on here :rocket:, but the [Chapter doc](https://docs.google.com/document/d/1ip2At9j6ba17odQwBbXDVU7qiLnHRnX8DflAfdQNb9c/edit?usp=sharing) could use some love. Think your team will be able to get an outline settled on by the end of the week?

**Comment by dougsillars** [comment]
I blogged on Base64 images a few years ago:

https://calendar.perfplanet.com/2018/performance-anti-patterns-base64-encoding/

and the relevant Query:

https://bigquery.cloud.google.com/savedquery/554669893916:ab8efa3724f847fdac26ae595afaf302
Best,
Doug

Douglass Sillars, PhD
+1   (608) 616-9572 US
+44 (0)7856204121 UK
@Dougsillars

**Comment by rviscomi** [comment]
@bseymour I've sent you an invite to join the 2020 Authors team, which we'll use to communicate to authors about upcoming milestones. Could you visit https://github.com/HTTPArchive to accept the invitation? I want to make sure you're included in our messages :)

@smatei also see #875 about creating custom metrics for 2019 queries that depend on the `response_bodies` data, which are exorbitantly expensive. There were [10 queries](https://github.com/search?q=bodies+repo%3AHTTPArchive%2Falmanac.httparchive.org+path%3Asql%2F2019%2F04_Media&type=Code&ref=advsearch&l=&l=) from this chapter last year that could be good candidates to reimplement inexpensively as [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/almanac.js) at runtime. @dougsillars did a lot of the analysis last year and may be able to help migrate them over.

**Comment by smatei** [comment]
@rviscomi I can see your point about the queries containing regexp search. I have checked the [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/tree/master/custom_metrics) folder. I will play a little bit with that project, and try to figure out how to implement/run/test them. I might not be able to help with them yet, but if I spend some time on them I might be able to help in the future. 

I also searched for the summary_response_bodies in the sample data, but found you request instead
[sample_data.summary_response_bodies ](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1032#issuecomment-658553387)

I have a question about the workflow. Will there be issues opened for the chapter? Create branches for these issues? Like "create sql for media 2020". And then merge this branch into master? If you have a document link, please point to it. I am trying to figure out things now.

**Comment by rviscomi** [comment]
> Will there be issues opened for the chapter? Create branches for these issues? Like "create sql for media 2020". And then merge this branch into master?

We're just using one issue per chapter to track all of the milestones: planning, analysis, writing, etc.

I've written up an [analysis workflow](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide#analysis-workflow) in the Analysts' Guide which should help clarify the process. Let's chat in [`#web-almanac-analysts`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack if you have any questions.

**Comment by tpiros** [comment]
@obto I'll be working on the outline this week.

**Comment by obto** [comment]
@tpiros sounds good. Remember the deadline to add [custom metrics](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide#almanac-custom-metrics-and-udfs) is the end of this week. So I'd focus on working with @smatei so you can figure out if you need to write any new ones

**Comment by tpiros** [comment]
I love this analysis from @dougsillars - something we should consider as well: (thread) https://twitter.com/dougsillars/status/1284743030499680257?s=20

**Comment by tpiros** [comment]
@smatei what's the best way to reach you?

**Comment by smatei** [comment]
> @smatei what's the best way to reach you?

@tpiros I have answered you on slack.

**Comment by rviscomi** [comment]
📟 @tpiros @bseymour @nhoizey @zcorpan @colinbendell @dougsillars @smatei Friendly ping to get the outline written and reviewed ASAP (overdue since July 20). The most important thing is to instrument the crawl with any needed custom metrics by **Monday, July 27**. Thank you for helping to keep this chapter on schedule!

**Comment by LeaVerou** [comment]
Question: would metrics like type of images used in CSS (PNG vs SVG vs ...) or linking type (embedded via data URI vs linked) be a good fit here, or would they be more appropriate in our CSS chapter?

**Comment by tpiros** [comment]
@rviscomi - @bseymour and I have added a draft outline. We will add the metrics as well. I have advised @dougsillars and @smatei to review the outline and hereby I am also pinging @colinbendell to add his thoughts! Thanks and I apologise for the delay.

**Comment by tpiros** [comment]
@rviscomi - is it OK for us to create a #media channel on slack (HTTP Archive)?

**Comment by nhoizey** [comment]
I just read the outline, and made some comments and suggestions.

Are the metrics within brackets awaiting validation?

I think "Using picture when srcset would be more appropriate" would be really interesting and useful.

**Comment by rviscomi** [comment]
@tpiros it's best to use the public GitHub issue / Google Doc to coordinate on the chapter. See Barry's great explanation in https://github.com/HTTPArchive/almanac.httparchive.org/issues/899#issuecomment-653488485 for more info/reasoning. That said, if you do need a Slack channel to be productive, I don't want to get in your way :)

**Comment by colinbendell** [comment]
Added some feedback. I'd really suggest we try and focus the scope to areas that will be a) different from last years report and b) areas that aren't "more of the same". meaning interesting for interest sake, but not really actionable. For example, the srcset and picture bits fall into this category.

**Comment by zcorpan** [comment]
@colinbendell do you mean srcset/picture is actionable, or not?

The art direction question would directly inform whether addressing  https://github.com/whatwg/html/issues/4968 is worthwhile

**Comment by colinbendell** [comment]
If you look at the data from last year, you'll find that nearly no one uses `<picture>` other than for `<source type=image/webp` and that all the `sizes=` are [generated (mostly bogus) entries ](https://almanac.httparchive.org/en/2019/media#use-of-sizes). The use of `<source media` was so very low from the HA dataset, and the values all appeared to be hand tuned, that I didn't dig any further. 

My main conclusion here is that `<source media`, `<img sizes` and even `<img srcset` are really powerful, but the tooling has been lacking to allow devs to easily adopt and utilize as a common tool. It's too abstract and the use appears to be very specialized rather than broad appeal. More patterns and common formulas are needed for broader adoption.

**Comment by nhoizey** [comment]
I agree that this is powerful and not used (well) enough.

Because Wordpress is so prevailing in data, it might be interesting removing it from results shown in https://almanac.httparchive.org/en/2019/media#fig-15 , to better understand how others do it.

I also wonder if browsers could start reporting `srcset` without `sizes` as hints in the dev console, even if there a default value.

All that to say that ignoring the topic in Almanach 2020 would not help raise awareness.

**Comment by obto** [comment]
@tpiros @smatei for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1ip2At9j6ba17odQwBbXDVU7qiLnHRnX8DflAfdQNb9c/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/05_Media

**Comment by tpiros** [comment]
@obto will do - both myself and @bseymour are away on an annual leave - I'll be back next week and will make all the necessary updates.

**Comment by Navaneeth-akam** [comment]
Hi, I had a chat with @paulcalvano about Almanac 2020 and would like to help with Media chapter. I'm new to this and would like to contribute as a reviewer.

**Comment by rviscomi** [comment]
@Navaneeth-akam great to have you!

@tpiros can you get them caught up?

**Comment by tpiros** [comment]
Welcome onboard @Navaneeth-akam. Please review the draft doc (link at the very top of this page) and let me know if you have any questions either here on on the #web-almanac-media channel on Slack.

**Comment by Navaneeth-akam** [comment]
Thanks @rviscomi !
@tpiros , will review the draft doc and let you know if I have queries.

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1SZGpCsTT0u1MFBrxed7HA9FLAloL1dS8ZIng986LvS8/edit#gid=2077755325

**Comment by rviscomi** [comment]
@smatei what's the status of this chapter's analysis?

**Comment by obto** [comment]
@tpiros in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by zcorpan** [comment]
Please remove me as reviewer for this chapter.

**Comment by obto** [comment]
@zcorpan Can do. Hope all is well and thanks for your help with the chapter thus far :+1:

**Comment by rviscomi** [comment]
@tpiros @bseymour could you update the milestone checklist at the top of this issue to reflect this chapter's current status? That helps us see how far along everyone is at a glance in #989. Thanks!

**Comment by tpiros** [comment]
Thank you @nhoizey and @Navaneeth-akam for your reviews!

Calling other reviewers! Our first draft is available for you to review. Please note that we'll be finalising this draft, so if you can please add your thoughts until 15h January to the [draft](https://docs.google.com/document/d/1ip2At9j6ba17odQwBbXDVU7qiLnHRnX8DflAfdQNb9c/edit?usp=sharing) document. Thank you 🙏

**Comment by bazzadp** [comment]
The content looks good to me. However I find it's only when we add the figures that it really comes alive so would be good to add some of those in to the chapter.

@smatei if you want I can help with those if you want?
@rviscomi pinged you to give me access.

Then once we're reasonably happy we should move to Markdown so we can see what it looks like on the site.

**Comment by bazzadp** [comment]
I went through the sheet after getting edit access and created some graphs. Can't say I fully understood all the metrics as wasn't involved in them, but hopefully didn't make too many mistakes.

Can you have a look @tpiros and see if you want to use any of those? You can copy and paste them into your draft.

Reach out on Slack if there's any of the other sheets you want graphs for but for the sheets where you only have 1 stats suggest you use the big figures, rather than graphs as little point in using a graph just to show two values. Example "big figure" [from the markup chapter](https://almanac.httparchive.org/en/2020/markup#fig-29) is below:

![Example big figure](https://user-images.githubusercontent.com/10931297/104044042-a0f10a00-51d4-11eb-8a05-fa562280dd59.png)
