### ISSUE TITLE
Third Parties 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#901]
# Part I Chapter 6: Third Parties

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
|@simonhearne | @tammyeverts @jzyang @exterkamp | @max-ostapenko | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @simonhearne

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1x8hhGIVYxvcDb3G4HGryW3yIOgLpvsNtQ_iHc_dMLEs/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/06_Third_Parties
[~results-sheet]: https://docs.google.com/spreadsheets/d/1uW4SMkC45b4EbC4JV1xKAUhwGN2K8j0qFy_jSIYnHhI/edit#gid=2077755325

**Comment by max-ostapenko** [comment]
I'd like to participate as an analyst in this chapter.

**Comment by rviscomi** [comment]
@simonhearne thank you for agreeing to be the lead author for the Third Parties chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1LRxXypzgi9lTjG5sMRPpaDvQ5OqHpqQ1Zyng01pTl3g/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/third-parties) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

To anyone else interested, we'd still love to have you contribute as a peer reviewer, data analyst, or coauthor as needed. Let us know!

**Comment by tammyeverts** [comment]
I'd love to be a reviewer for this chapter!

**Comment by rviscomi** [comment]
Great thank you @tammyeverts, it's great to have you on board again! I'm also super excited because this is the first chapter to have all three author/reviewer/analyst roles filled 🥳

**Comment by obto** [comment]
Hey @simonhearne, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Can you remind your team to properly add and credit themselves in your chapter's Google Doc?
3. Anything you need from me to keep things moving forward?

**Comment by rockeynebhwani** [comment]
@simonhearne  - Please see this thread https://discuss.httparchive.org/t/how-many-and-which-resources-have-timing-allow-origin-for-resource-timing/152/10. 

I think it will be good idea to call out most used third parties without Timing-Allow-Origin headers in this year's third party chapter and hope some of these third parties start to pay attention. What do you think?

**Comment by simonhearne** [comment]
Hey all, back(-ish) from PTO today.

Thanks to those offering help, could you please add yourself to the relevant line in the *Content Team* section of [the doc](https://docs.google.com/document/d/1x8hhGIVYxvcDb3G4HGryW3yIOgLpvsNtQ_iHc_dMLEs/edit#):

@tammyeverts - *Reviewer*
@jzyang - *Reviewer*
@max-ostapenko - *Analyst*

I think this gives us enough folks to start preparing the content! I would appreciate feedback on the [outline section](https://docs.google.com/document/d/1x8hhGIVYxvcDb3G4HGryW3yIOgLpvsNtQ_iHc_dMLEs/edit#heading=h.vqdmpb884vdu), comments in the doc preferred.

**Comment by simonhearne** [comment]
For ongoing communication, what would you prefer:

👍🏻 use this issue
🚀 comments & chat in google doc
👀 slack channel in the HTTPArchive slack

**Comment by max-ostapenko** [comment]
Sent a file access request.

**Comment by rockeynebhwani** [comment]
@simonhearne - moving this from slack. @rviscomi  suggested this chapter for this topic. 

It will be good to cover usage of Tag Manager in this chapter.  For example -

- % of sites using more than one tag manager (e.g. GTM / Adobe DTM / Signal on HomePage)
- % of sites using multiple instances of same tag manager provider (Example - https://www.schuh.co.uk/ .. two different instances of GoogleTagManager). I think you are aware why they do this.
- % of third parties initiated from Tag Managers Vs Directly on sites where TagManager is in use.

I see there is a Tag Manager category in Wappalyzer (only 5 tag mangers so far but it can be easily improved)

Thoughts?

**Comment by bazzadp** [comment]
Size of tag manager JS. They can quickly get out of control and get massive when old tags (that often aren’t ever even fired!) continue to hang around clogging up the JS.

**Comment by obto** [comment]
@simonhearne @max-ostapenko for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1x8hhGIVYxvcDb3G4HGryW3yIOgLpvsNtQ_iHc_dMLEs/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/06_Third_Parties

**Comment by max-ostapenko** [comment]
Thanks for a heads up.
Will go and update the state.

**Comment by exterkamp** [comment]
Is this section still in need of reviewers? I'd be happy to help.

**Comment by rviscomi** [comment]
Thanks @exterkamp! @simonhearne can you help onboard Shane?

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1uW4SMkC45b4EbC4JV1xKAUhwGN2K8j0qFy_jSIYnHhI/edit#gid=2077755325

**Comment by rviscomi** [comment]
I learned about some really interesting work @patrickhulce has been doing on correlating third parties to Core Web Vitals performance. I suggested that could be an interesting area of exploration for this chapter and he's open to joining the team as a reviewer. @simonhearne is that something you'd be interested in?

**Comment by patrickhulce** [comment]
Happy to help but I also understand if we don't want too many (repeat) cooks in the kitchen :) let me know what would be most helpful here!

**Comment by max-ostapenko** [comment]
@simonhearne [first data and charts](https://docs.google.com/spreadsheets/d/1uW4SMkC45b4EbC4JV1xKAUhwGN2K8j0qFy_jSIYnHhI/edit#gid=2077755325) are ready for review.

**Comment by max-ostapenko** [comment]
@patrickhulce did you have any particular query in mind providing correlation analysis?

> Happy to help but I also understand if we don't want too many (repeat) cooks in the kitchen :) let me know what would be most helpful here!

@patrickhulce did you have any particular query in mind providing correlation analysis?

**Comment by patrickhulce** [comment]
> did you have any particular query in mind providing correlation analysis?

The correlation analysis @rviscomi was referring to in https://github.com/HTTPArchive/almanac.httparchive.org/issues/901#issuecomment-685964320 was separate from HTTP Archive and involved blocking.

My only suggestion I have on the current queries is that several of them focus on a metric that is completely normalized by the frequency and so it ends up yielding mostly obscure, really uncommon third-parties that might not be the most interesting to analyze (and have "unknown" categories as a result too). For example, it might be more useful for most readers to look at "most popular 100 sorted by median body size" or something instead of "top 100 by median body size".

If there are big ones missing from categorization we can also try to plug that gap, we have ~98% coverage by request count last I checked but coverage as % of all possible third-parties is much, much lower.

**Comment by obto** [comment]
@simonhearne in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by rviscomi** [comment]
I've added @exterkamp as a reviewer, per his offer to help in the Slack channel. Shane, can you add your info to the [2020.json](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2020.json) config file? The [first draft](https://docs.google.com/document/d/1x8hhGIVYxvcDb3G4HGryW3yIOgLpvsNtQ_iHc_dMLEs/edit?usp=sharing) is coming along but not done yet, so there are still opportunities to help. Thanks!

**Comment by rviscomi** [comment]
@simonhearne please have your markdown submitted by EOD today to be included in Wednesday's launch.
